### ISSUE TITLE
Norwegian Bokmål translation appears in unrecognisable language (probably dutch)

### ISSUE THREAD

**Issue by Baardi** [windirstat/windirstat#100]
![bilde](https://github.com/user-attachments/assets/2c4b0f14-f637-4d03-91bf-3421ba85df65)

I think it would make more sense to use English as a fallback-language when translations are missing. It's really hard to find the language-setting when everything is in (probably) dutch.

**Comment by NoMoreFood** [comment]
Odd.  I will admit that the Norwegian translation was 100% and possible it misinterpreted my request.  If I regenerate it, would you be willing to fix any errors?

**Comment by NoMoreFood** [comment]
@Baardi Can you see if this version is better?

https://github.com/windirstat/windirstat/releases/tag/beta/v2.0.2/2024-10-17

And if you're willing to tune the translation, here is the file to update:

https://github.com/windirstat/windirstat/blob/master/windirstat/res/langs/lang_no.txt

If you put that file next to WinDirStat.exe, it will read it on startup.

**Comment by Hoaas** [comment]
Encountered same issue. https://github.com/windirstat/windirstat/releases/tag/beta/v2.0.2/2024-10-17 looks to be working here atleast.

![image](https://github.com/user-attachments/assets/c059d3b6-4049-4c00-ade7-d1635dbf6f9d)

**Comment by Baardi** [comment]
> Encountered same issue. https://github.com/windirstat/windirstat/releases/tag/beta/v2.0.2/2024-10-17 looks to be working here atleast.
> 
> ![image](https://private-user-images.githubusercontent.com/414791/377746040-c059d3b6-4049-4c00-ade7-d1635dbf6f9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyODEzNzMsIm5iZiI6MTcyOTI4MTA3MywicGF0aCI6Ii80MTQ3OTEvMzc3NzQ2MDQwLWMwNTlkM2I2LTQwNDktNGMwMC1hZGU3LWQxNjM1ZGJmNmY5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxOTUxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTgzN2NjMjA4ZjFhM2U1NGY3OGFjYTc0MjliZWRhNzgzMGNlOTVhMDM4M2UwMjA0ZGZjZGQyNzczMDdlZjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KIafMAfv8-XpNQkWPKt_KDUSfuem9odJzbSbvqjUkok)

It works for me too on that version @NoMoreFood

**Comment by NoMoreFood** [comment]
Thanks for confirming!  I'll make an official production release in the next day or two (there's nothing different about how it's built so feel free to use that one).

**Comment by NoMoreFood** [comment]
Now available in new release.  Should be in WinGet shortly.  If you have any tweaks to the translation fix, please consider putting in a pull request.  Thanks!
