### ISSUE TITLE
Docker images cause "Physical Size" number to explode

### ISSUE THREAD

**Issue by MatthewSteeples** [windirstat/windirstat#101]
Congrats on the new release. Looks amazing. I've found an issue with the way that the sizes are calculated when Docker images are involved...

My C Drive is 500gb and this is what Windirstat shows as my largest few folders...

![image](https://github.com/user-attachments/assets/ae162fbd-5e39-4da5-9713-b1be108c55dc)

Hope that's enough information but if you need any more let me know and I'll see what I can do

**Comment by MatthewSteeples** [comment]
The cause seems to be that the "Physical size" of each file detected in the layer is reported as 4gb, no matter what the logical size is

![image](https://github.com/user-attachments/assets/f170449e-3263-4766-bc53-e8f3609e62b7)

**Comment by NoMoreFood** [comment]
Thanks for reporting.  I will try to reproduce this.  If you right click on an explorer window and read the size, is it also detected as 4GB?

**Comment by NoMoreFood** [comment]
Okay, I'll admit running docker is not my specialty.  Could you give me some basic commands or instructions to create files like the ones you have in the screenshot?

**Comment by NoMoreFood** [comment]
@MatthewSteeples   Can you see if this version operates better?

https://github.com/windirstat/windirstat/releases/tag/beta/v2.0.2/2024-10-17

**Comment by MatthewSteeples** [comment]
They show as 0 bytes for "size on disk". I'm assuming it's because Windows is doing something odd at the FileSystem level if these files are shared between multiple layers (like symbolic links)

The new version you've provided works great

**Comment by NoMoreFood** [comment]
Awesome.  This will be included in the production 2.0.3 release which should be out in the next day or two.  Thanks for reporting!

**Comment by NoMoreFood** [comment]
Now available in new release.  Should be in WinGet shortly.
