### ISSUE TITLE
Name of hovered file should stay in status bar

### ISSUE THREAD

**Issue by vlakoff** [windirstat/windirstat#109]
Since I use the legacy WinDirStat 1.1.2, I am very used to hover boxes and look at the file names in the status bar.
It's by far my most proeminent workflow in WinDirStat, and I guess it's the same for many other people.

I just noticed in WinDirStat 2.0.3 that the name appears for only about 1 second, then the status bar goes back to displaying the currently selected file (which, additionally, isn't very helpful: the tree view already shows the currently selected file, in a more helpful way).

Current workarounds to keep the hovered file in the status bar:
* Keep the mouse always moving.
* Click each and every time.

Both of these workarounds are not acceptable…

Please, restore 1.1.2 behavior which was just perfect.

**Comment by NoMoreFood** [comment]
Yeah, this might have been a regression in 2.0.3.  I will get this fixed up in the next few days.  Thank you for reporting.

**Comment by NoMoreFood** [comment]
@vlakoff Can you see if this version addresses the issue for you?

[WinDirStat.zip](https://github.com/user-attachments/files/17489947/WinDirStat.zip)

**Comment by NoMoreFood** [comment]
@vlakoff Other than your comment in the code, did that address the behavior?

**Comment by vlakoff** [comment]
Yes, the issue is fixed with this asset.

I also tried a few releases, and the regression has been introduced in version 2.0.2. I would guess it was caused by https://github.com/windirstat/windirstat/commit/70a184f6497c17b91d6083878c9a4e1b194e871c.

**Comment by NoMoreFood** [comment]
I suspect you are correct.

**Comment by vlakoff** [comment]
Has been fixed by https://github.com/windirstat/windirstat/commit/d6959a966996826bf3eab2ae0d48cdca3d191c10, deployed since [WinDirStat Beta 2.0.4 / 2024-10-26](https://github.com/windirstat/windirstat/releases).
