### ISSUE TITLE
stops at 1 713 108 files

### ISSUE THREAD

**Issue by fomox** [windirstat/windirstat#112]
Hi!

Im running windirstat on a network drive, and whenever i reach 2,4tb or 1 713 108 files it stops, thats about 20% of the total files on the drive. The application works fine up until that point and after, but when i reach it it just quits the scan and presents me with the results. I have tested on two different machines and two different network drives, all combinations give the same result

**Comment by NoMoreFood** [comment]
@fomox There is certainly no limit to the scans (at least with the new version).  Which version are you running?

**Comment by fomox** [comment]
2.0.3 x64 windows

**Comment by NoMoreFood** [comment]
Can you confirm you are running as admin and have permissions to the entire volume?  If you Show Unknown, does it account for the remaining space?

**Comment by fomox** [comment]
Tried running as admin.
I dont have access to the entire share, but still about 90% of it so it quits too soon.

will check unknown monday

thanks for the response so far!

**Comment by fomox** [comment]
Unknown accounts for the remaining space yes!

**Comment by NoMoreFood** [comment]
@fomox So I've ran this on 20TB volume with many million files.  Is this a Windows file server? NetApp? Samba?

**Comment by fomox** [comment]
@NoMoreFood Its NetApp. We`ll try running it with an account that has access to the whole share to see if we get different results. Thanks for looking into this, appreciate it!

**Comment by NoMoreFood** [comment]
@fomox Sounds good.  I would appreciate any follow-up you have so we can improve WinDirStat, if necessary.  Any account that's actually an 'Administrator' on the NetApp should be able to leverage backup/restore privileges and break through any permissions barriers.

**Comment by fomox** [comment]
@NoMoreFood
Hi!

We got the same results with an admin account that has access to the whole NetApp. Is there any log files im not aware of that i can look at to try and figure out why its stopping early?

**Comment by NoMoreFood** [comment]
You try running the attached which should pop up a console in the background that shows when it can't enumerate a directory.  Make sure run locally using 'Run As Administrator' and also run as someone with full permissions on the filer.

[WinDirStat_x64.zip](https://github.com/user-attachments/files/17646683/WinDirStat_x64.zip)

The other thing I thought of -- since this is a NetApp -- you may want to check your snapshots and how much they are allocating.  Those can eat space and don't always appear as enumerable files.

**Comment by fomox** [comment]
@NoMoreFood 
Thanks for helping me with this!

Sadly no error messages appearing. My suspicion is that you are right and it might be the snapshot allocations that are tricking me into thinking this exits prematurely. I need to contact the vendor to figure that out, but ill let you know the results.

![image](https://github.com/user-attachments/assets/60649bea-fab2-4ee1-93cc-3afc3b4f4145)

**Comment by NoMoreFood** [comment]
@fomox Sounds good.  Just so you know all, those errors are indeed "Access Denied" errors so any files within those will be left uncounted.

**Comment by NoMoreFood** [comment]
Going to close this for now since there is nothing actionable.  I will reopen if that changes.
