### ISSUE TITLE
File delete window

### ISSUE THREAD

**Issue by tron2k** [windirstat/windirstat#113]
Hello,

in the file deletion window it is not possible to go to Yes Button with the left arrow key.
![image](https://github.com/user-attachments/assets/dccd1f73-17fd-49b4-8c04-43219dfce630)

And after deletion, the deleted file is not deleted in the file view.
![image](https://github.com/user-attachments/assets/774ab96a-b61a-4d27-819c-850bf394cbee)

WinDirStat Version 2.0.3

**Comment by NoMoreFood** [comment]
@tron2k 

Can you confirm this fixes both issues?  Thanks for reporting!

[WinDirStat.zip](https://github.com/user-attachments/files/17513811/WinDirStat.zip)

**Comment by NoMoreFood** [comment]
Alright, let's try that again. I think I misunderstood what you were saying originally.

[WinDirStat.zip](https://github.com/user-attachments/files/17526816/WinDirStat.zip)

**Comment by tron2k** [comment]
Thank you, it works now.

**Comment by tron2k** [comment]
One small addition.
If you click on the folder path, the checkbox “Individual Folder” is not set.

**Comment by NoMoreFood** [comment]
@tron2k Try this please:

https://github.com/windirstat/windirstat/releases/tag/beta/v2.0.4/2024-10-26

**Comment by tron2k** [comment]
I haven't noticed anything else.
![image](https://github.com/user-attachments/assets/c8940452-cb00-4a97-adf6-027797f99297)
If “Individual Drives” was selected first and you deselect all drives and then go to “Individual Folder”, the OK button is deactivated.

**Comment by NoMoreFood** [comment]
Can you see if your latest comment was address in this release?

https://github.com/windirstat/windirstat/releases/tag/beta/2.1.0

**Comment by tron2k** [comment]
Thank you, now it's okey
