### ISSUE TITLE
Crash when exporting to CSV on Windows Server 2016

### ISSUE THREAD

**Issue by UweTrottmann** [windirstat/windirstat#114]
After running a scan and then trying to export the app crashes after picking a file to save to.

I tried but failed to narrow down the cause (portable mode, German vs. English language, save to NTFS vs. ReFS partition). On another machine with Windows 11 everything works as expected.

Here are some details from the crash event that may help to identify the source of the crash:

Version: 2.0.3.832
Operating system: Windows Server 2016
Locale: Germany
Error code: 0xc0000409
Error offset: 0x000000000026e0c9

I could not find any info on how to provide a crash report, so let me know if and how I can provide any additional details.

And thank you for picking up development of one of my favorite Windows tools!

**Comment by NoMoreFood** [comment]
@UweTrottmann  Thanks for reporting.  If you do a very small scan (a single directory), do you also the problem on Windows Server 2016?

**Comment by UweTrottmann** [comment]
Yes, it also crashes for a directory that only contains a few files.

**Comment by NoMoreFood** [comment]
I found the issue.  Apparently a library we use doesn't fully work on Windows Server 2016. I worked around it. I'll have a new beta version posted in a bit.

**Comment by NoMoreFood** [comment]
@UweTrottmann  

Can you try out this version: https://github.com/windirstat/windirstat/releases/tag/beta/v2.0.4/2024-10-26

**Comment by UweTrottmann** [comment]
Saving to and loading from a CSV file works now, even for folders with many sub-folders and files.

I had a look at the commit and the chrono library truly does not appear [fully supported before Server 2019](https://learn.microsoft.com/en-us/cpp/standard-library/chrono?view=msvc-170#requirements).

Thanks for the fix!

**Comment by NoMoreFood** [comment]
Released with https://github.com/windirstat/windirstat/releases/tag/release/v2.1.1
