### ISSUE TITLE
Window Server 2008 R2 - black area instead of colored files layout and toolbar issues

### ISSUE THREAD

**Issue by Kbdq** [windirstat/windirstat#119]
Look screen attached. All settings are default. Latest portable version x64.

1. Buttons in toolbar looks incorrect.
2. Black area instead of colored files layout - probably the reason is absent colors for different file types at top right area?

![image](https://github.com/user-attachments/assets/9ef6773b-c0ef-4dfc-9008-1d28c528b387)

**Comment by NoMoreFood** [comment]
I swear I tested it on Windows Server 2008 R2.  I'll take a look and see if it's fixable, but it's possible we may just need to drop it from the support list :-(

In case you don't have it, here is the link to download the 1.x version: https://windirstat.net/legacy.html

**Comment by NoMoreFood** [comment]
I just tested on Server 2008 R2 and I cannot reproduce this issue.  The interface renders properly.  Are you running with very low colors or anything else that might make your situation unique.

**Comment by NoMoreFood** [comment]
Update: I was able to produce the issue, but only over RDP (i.e., not when running on the physical/virtual console). I'm guessing this is a limitation with the graphics capabilities of the RDP version that's included with Server 2008 R2.  I'll research it a bit more, but I don't think this is something we're going to be able to easily workaround.

**Comment by Kbdq** [comment]
Yes, it might be related to RDP - I don't have physical access to the machine to check how it works on the physical console. But I must say that old version (1.1.2) works fine under RDP and is free of this issue. This is OK if you will not fix it - I perfectly understand that 2008R2 is out of support for a long time already. Thank you anyway and thank you for working on this old but very useful software.
