### ISSUE TITLE
Feature Request: Disable Explorer right click integration

### ISSUE THREAD

**Issue by Rockz1152** [windirstat/windirstat#120]
As a long time user, thanks for keeping WinDirStat updated.

The recent update added a new option in Window explorer when right clicking on a directory. Adding an option to disable this integration would be very appreciated.

Thank you.

**Comment by NoMoreFood** [comment]
Is it causing an issue for you?

**Comment by Rockz1152** [comment]
To be honest, I only use WinDirStat once or twice a year. Seeing it popup every time I right click on something is just a little distracting. It's not that I can't disable the integration myself, which I have done. It's that I feel others who are less technically inclined might also want to disable the integration as well.

**Comment by NoMoreFood** [comment]
When you install/change, it's a sub-option under the main feature you can deselect.

**Comment by Rockz1152** [comment]
I see now, that worked on my test system.

When you install with winget or ninite, they both use silent installs ao you don't get to see the full installation options. I guess that makes this setting a little hard to find.

Moving it to somewhere in "WinDirStat - Settings" may make more sense, like General/Advanced. I know that's as simple as it sounds since the setting is being handled by the packager and not the application right now.

**Comment by tron2k** [comment]
@NoMoreFood 
I agree with Rock. I recently installed WinDirStat via WinGet and now have the entry in the context menu.
Personally, I don't like it when “every” program adds itself there.

**Comment by Asinin3** [comment]
Agree on this - I don't like that the new context menu options are on by default. Most people who install Windirstat are doing so to do a few scans manually on a rare occassion and not something they will be using all the time so the extra context entry bloats the right-click menu.

Would prefer it to be a checkbox during install to turn it on if you want it.

**Comment by NoMoreFood** [comment]
I'll consider making it more obvious during the install.

**Comment by Asinin3** [comment]
@NoMoreFood That works, but can you please add a switch via command line where you can turn the context menu off? I tried testing it with the linked beta, but it wouldn't work with the /q switch for some reason even though 2.0.3 does.

**Comment by NoMoreFood** [comment]
@Asinin3 In the next version, you'll be able to prevent it from being enabled by doing DISABLE_CONTEXTMENU=1.

**Comment by cars11** [comment]
> When you install/change, it's a sub-option under the main feature you can deselect.

also having this problem.

why would this be an installer setting on and not a program setting? you do not expect to have decisions like that in the installer and just click through it because like in 99% of other programs all relevant settings are configured in the app and not the installer.

**Comment by NoMoreFood** [comment]
Released with https://github.com/windirstat/windirstat/releases/tag/release/v2.1.1
