### ISSUE TITLE
Feature request: refresh selected while scan running

### ISSUE THREAD

**Issue by rdp** [windirstat/windirstat#121]
If I start a scan, and it shows, ex: "$Recycle.bin" as taking a lot of space, so I clean the recycle bin, then what I wish I could do is go to windirstat and tell it to "refresh selected" on the recycle bin, while it is still scanning.  Doesn't seem to let me at present, even if I pause the scan.
Thank you for your development time on this, most useful utility :)

**Comment by NoMoreFood** [comment]
I completely understand the desire for this, but the logic that handles scanning is not adaptable to this request and trying to adapt it could be hazardous to stability.  According, closing this as "not planned".  Possible we can revisit in the future.  Sorry :-(

**Comment by rdp** [comment]
Actually since it's much faster now this may be less annoying to not have so...thank you!  (Extra credit if you could change the right click menu to have "Delete Permanently" (greyed out while still doing a run) say "Delete Permanently (not yet available while doing scan)" though greyed out is alllmost clear as to why...
