### ISSUE TITLE
feature request: delete files in folder

### ISSUE THREAD

**Issue by rdp** [windirstat/windirstat#122]
Sometimes I run into a folder full of "stuff" like named "Temp" or something.
What I'd like to do is delete the files out of there, without deleting the folder itself (which may still be useful).  I.e. just *try* to delete everything you possibly can out of there...doesn't seem an option today.

Cheers!

**Comment by NoMoreFood** [comment]
Available in this beta release if you want to give it a try:

https://github.com/windirstat/windirstat/releases/tag/beta/v2.1.0/2024-11-01

**Comment by rdp** [comment]
Seems to work.  Though it doesn't show the "greyed out" grid while it refreshes after, like other delete options seem to, but not a big deal :)  Neither does "refresh selected" ... (?)

Extra credit if it could say something after like "could not delete all files" when that is the case.  Though I noticed "delete permanently" also doesn't warn if it can't delete something...kinda low prio.  Thanks!

**Comment by rdp** [comment]
Also unrelated, the "About WinDirStat" window, it's a tiny bit hard to tell that one is on a beta there (since releases also list a git commit)...:)

Naming the msi files with their version might be useful in certain cases, if you want extra extra credit, ha ha, cheers! :)

**Comment by rdp** [comment]
Looks like if I have a portion of the directory "in use" then some other portions of it won't get deleted (like some files, though not in use)... :| 2.1.0 beta :)

**Comment by NoMoreFood** [comment]
Released with https://github.com/windirstat/windirstat/releases/tag/release/v2.1.1
