### ISSUE TITLE
Make left and right arrow key behaviour consistent

### ISSUE THREAD

**Issue by achtchaern** [windirstat/windirstat#123]
Hi there,

I absolutely love your contributions to WinDirStat. For me, it's almost perfect now, with one exception:

In my opinion, the fact that, in the tree view, the right arrow key immediately expands the folder feels wrong to me. Firstly, it's not consistent with the left arrow key (which doesn't immediately collapse the current folder, but moves the focus to the top) and it's not like the classic WinDirStat behaved.

My suggestion would be the following:

In TreeListControl.cpp, from line 792, change the code as follows:

Before:

            if (!items[0]->IsExpanded())
            {
                ExpandItem(FindTreeItem(items[0]));
            }
            if (items[0]->IsExpanded() && items[0]->HasChildren())
            {
                SelectItem(items[0]->GetSortedChild(0), true, true);
            }

After:

            if (items[0]->IsExpanded() && items[0]->HasChildren())
            {
                SelectItem(items[0]->GetSortedChild(0), true, true);
            }
            if (!items[0]->IsExpanded())
            {
                ExpandItem(FindTreeItem(items[0]));
            }

Just swap the two conditions. Do you have an issue with my suggestion?

Best regards

**Comment by NoMoreFood** [comment]
I agree.  See if this version works better for you:

https://github.com/windirstat/windirstat/releases/tag/beta/2.1.0

**Comment by achtchaern** [comment]
Thank you!!! Perfect! Fantastic.

**Comment by DanielRouxSA** [comment]
Personally, I prefer it the way it is currently. Moving focus to the parent node first and then closing it on the second left-arrow press is consistent with the way most tree views work on Windows. Intentionally breaking from this convention would feel odd to me.

**Comment by NoMoreFood** [comment]
Released with https://github.com/windirstat/windirstat/releases/tag/release/v2.1.1
