### ISSUE TITLE
716GB Unknown files

### ISSUE THREAD

**Issue by Burger23333** [windirstat/windirstat#124]
I have a 1TB SDD that shows 716GB as UNKNOWN. How do I either delete these files- or, ideally, discover the files names? Thank you, Chris

![WinDirSat](https://github.com/user-attachments/assets/0872f925-445f-435f-87cc-778e00d6a98e)

**Comment by NoMoreFood** [comment]
Try using the new version and be sure to run it as an administrator.

**Comment by Burger23333** [comment]
Thanks for your prompt reply.

I uninstalled newest version as an Adminstrator. Unforunately, minimal change in the UNKNOWN that still takes up anbout 700GB of my drive. I am trying to delete these mystery files without having to reformat the disk. Any other ideas
![WinDirSat 2](https://github.com/user-attachments/assets/a5ad34d3-3af7-444d-ab63-ba524f717f85)

**Comment by NoMoreFood** [comment]
Wow. That is a mystery. I have two suggestions:

1. Run `chkdsk /f c:` and allow it to scan at reboot.  It's possible there is some corruption on the file system that needs to be fixed.
2. It may be worthwhile to try a tool that directly reads the MFT like WizTree.  Something must be lurking in the non-addressable area of the file system.

If either of those help, I'd appreciate following up in the event we can improve WinDirStat.

**Comment by Burger23333** [comment]
![image](https://github.com/user-attachments/assets/6dbfe48e-445f-4dbf-8f28-e168ad50dc64)
Thanks so much for Wiz-Tree. It found the culprit: CSC Folder. I have no idea what it is- I saw the the upper level folder, ServerFolders2 contains all the files. Serverfolder2 is a folder on a networked computer where I keep all my backups. I deleted all files in Drive C and drive D, and I now have 629GB Free space. Problem solved!

Have you ever heard of CSC Version 2.0.6? I do not believe I installed it. I will watch file size and see if this is coming from my Backup server- or my computer.

Thanks again
Chris

**Comment by NoMoreFood** [comment]
Odd that WinDirStat didn't find that; it definitely shows up on my computer but I don't fully activate CSC.  CSC is a Windows built-in component that handles caching of files from other volumes so they can be accessed when offline.  I suspect some other piece of software you have installed enabled CSC.  Generally, you don't want to mess with it directly.  If this happens again, you're probably better off running this from an elevated command prompt and then rebooting: `reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Csc\Parameters /v FormatDatabase /t REG_DWORD /d 1 /f`.  This should gracefully clear out CSC after the next reboot.

Regardless, glad to hear things are better for you.

**Comment by NoMoreFood** [comment]
@Burger23333 Thanks to your report, I found why WinDirStat could not scan that area and I will include the fix in the next release.
