### ISSUE TITLE
improper physical and logical size of drive

### ISSUE THREAD

**Issue by rnmerchant** [windirstat/windirstat#129]
Odd improper reporting of drive size.
On the initial screen:   "WinDirStat - Select Drives" my D drive is properly reported as 3.63TB  (4 terabytes).
However, on the subsequent main WinDirStat screen the D drive shows up as 2.2TB physical size, 70% full.  This is inaccurate...
![Screen Shot 11-04-24 at 11 02 AM](https://github.com/user-attachments/assets/b1b4761a-af17-4f90-bb00-0fe3e52b149e)

**Comment by NoMoreFood** [comment]
A few things.  The summary statistics on the drive selection dialog are reported a volume level where as the values in your screenshot are obtained by enumerating all the files and adding them up.  This summation will not account for anything in can't scan which includes files it does not have access to or file system overhead.  So before we think about this too hard, first to go 'File' and 'Run Elevated' and see if the numbers are closer to the reported values.

**Comment by rnmerchant** [comment]
Thanks NMF.
I ran it as administrator and got similar results.   I can see that WinDirStat 'physical size' and 'logical size' columns are correctly reflecting the combined file sizes.  And I would guess that the "Subtree Percentage" reflects percent file sizes on the whole system in each 'subtree' location.   I was initially thinking that this represents the percent of the drive space occupied but I think that is not correct.  I think that it would be handy if the amount of empty space on each drive (aka 'subtree') was reported. ('Freespace' should report that I would have thought but it doesn't seem to do so).

![Screen Shot 11-05-24 at 08 57 AM](https://github.com/user-attachments/assets/84e4fa7f-bc5d-45b0-9c5e-e73e60323f51)

**Comment by NoMoreFood** [comment]
In the most recent released, I added the percentage free adjacent to the label to make it implicitly differentiable from the subtree percentages.
