### ISSUE TITLE
Unable to find duplicate files

### ISSUE THREAD

**Issue by hypesquare** [windirstat/windirstat#131]
Hello
Just started using windirstat today, so this might be a user issue, but it seems that the duplicate file search isn't working. I have tried running it elevated, checked settings, and ensured there was a duplicate file. I looked online and found no support documentation to help with this issue. 
![image](https://github.com/user-attachments/assets/8a6e0934-9d09-4727-acf2-c3cf8c3cab19)

**Comment by NoMoreFood** [comment]
Did you check the box on the first screen where you select the drives?

**Comment by hypesquare** [comment]
I am blind appearntly my aplogies.
![image](https://github.com/user-attachments/assets/6b6ba010-512b-4831-a424-efebf42a56a3)
