### ISSUE TITLE
It doesn't work anymore! Help! (WindirStat)

### ISSUE THREAD

**Issue by philumax** [windirstat/windirstat#132]
Hello.
My PC : Asus Rog strix x299-E Gaming II.
Device Name 980Pro1V2
Processor Intel(R) Core (TM) i9-10980XE CPU @ 3.00GHz 3.00 GHz
Installed RAM 64.0 GB (63.7 GB usable)
System Type 64-bit Operating System, x64 Processor
Edition Windows 11 Professional
Version 23H2
Installed on ‎Sunday ‎June ‎2, ‎2024
OS Build 22631.4391
Experience Windows Feature Experience Pack 1000.22700.1047.0
I wanted to install WindirStat (X64 or X86): for the installation, no problem. At launch, with the choice "all drives" or "some drives", indexing is done at full speed. Just click on a disk and it blocks. Whether it's the latest version (2024\11\01) or the "windirstat.net" version. It bothers me a little, I've always used it. Note that I just changed my processor (I7 9800X for an i9-10980XE). With the i7, no problem.
Everything is affected too...
Thanks.
See you later.

PHILUMAX
![gestiondisque](https://github.com/user-attachments/assets/7a398780-6c3e-46a3-9aaa-233132e28249)

**Comment by NoMoreFood** [comment]
Can you be a little bit clearer on what the behavior you're seeing is?

**Comment by philumax** [comment]
Hello.
Thank you for your answer.
I will first say what I did today, because something must have happened...
On the mentioned machine, I have a dual boot, Windows: in case one breaks down, I always have the other, if only to have access to the NET.
I don't go there often (in fact, I hadn't been there since September). On this location (which has its own disk (it's not a partition)), there are some tools, like Aomei, EasyBCD etc.... This OS is not cluttered, with a lot of programs, like the other one.
I went there today, because it also has Windirstat and Everything.
However, as it had been a long time since I had used it, there were a lot of updates to do: I did them.
Then, I tried Windirstat and Everything.
It works!
Except, Everything, which at the beginning, crashed: when I wrote a search in the bar, after the second letter, it blocked and the mouse went underneath. Forced to delete it, via the task manager.
I searched in its options and I found an option, which allowed it to be launched by a simple click, which I had never noticed until then! I activated it. That's all I changed, on this OS, with the updates.
When I left it, everything worked.
There, I returned to my main OS: Oliver Schneider, whom I had contacted, gave me some leads, like the possibility of a persistent reader.
Apart from the CDROM, there was an "alcohol" reader, which I use from time to time: I deactivated it, with its other features, via the device manager: no change.
Today, after thinking about it, I said to myself that Rainmeter, which I use in conjunction with Gadgets 5.5.1 from SilverAzide, had a display of trheads and since my processor with Hypertreading now has 36, it could do something. I closed Rainmeter and launched Everything, which I modified, to launch it with a single click: it works! That's all I modified, on this software.
Then, I launched Windirstat, but an old version: 1.1.2: it works!
However, logically, I must also try the latest version, to know if the malfunction is due to the modifications of the latest version or something else (Windows?).
I will do the tests and I will keep you informed.
It's a bit long, but I was asked to detail.
Thank you.
See you later.

**Comment by philumax** [comment]
As promised, I'll keep you posted: I uninstalled the old version (1.1.2) and installed the X86 version 2.1.0.890 (and even the X64 version)
So it works, except if I right-click on a "disk" or a directory. There, it crashes!
I went back to version 1.1.2: uncratable!
I had Google Drive, I left it, before doing the tests: it didn't change anything.
So, I'm going to keep this version (much slower) that works, while waiting for something better.
Thanks.

**Comment by NoMoreFood** [comment]
It sounds like you may have a Explorer shell extension that is making the dynamic Explorer context menu blow up.  I'll compile a version that does not have that enabled to see if that helps. If it does, we can make a settings option to disable the right-click Explorer context menu integration.

**Comment by NoMoreFood** [comment]
Can you see if this version has the same issue?

[WinDirStat.zip](https://github.com/user-attachments/files/17683121/WinDirStat.zip)

**Comment by philumax** [comment]
Thanks.
I'll put this version on the desktop and I'll see tomorrow: I'm creating (and I'm going to test) the Windows recovery drive, but, it takes time...

**Comment by philumax** [comment]
Hello.
I tried the X64 and the proposed X86.
First observation, there is no installation: that's surprising!
So, the X64 blocks and the X86 does not block!
See you later.

**Comment by NoMoreFood** [comment]
Can you better explain what you mean by "blocks"?  There should be no difference between the x86 and x64 compiles other than x64 can handle extremely large number of files.  I'm guessing there's some sort of security software getting in the way.

**Comment by philumax** [comment]
It freezes. The mouse, passes behind. Only the close cross is available.
Clicking on it, makes the Windows box "close or wait" appear.
Click on "close", gives: report to Windows.
I don't have any other antivirus than Defender.

**Comment by NoMoreFood** [comment]
Can you do the following to help me debug:

1. Launch the attached version [WinDirStat_x64.zip](https://github.com/user-attachments/files/17688914/WinDirStat_x64.zip)
2. Reproduce the problem
3. Go to Task Manager
4. Locate the Details area where the processes are listed
5. Right click on WinDirStat_x64.exe
6. Choose the option to create a dump file
7. Send the file it creates to berns@uwalumni.com

![image](https://github.com/user-attachments/assets/3ed5c91e-bab0-4428-99e9-4131247507b5)

**Comment by NoMoreFood** [comment]
Thanks for sending the dump.  Can you see if this version as the same issue:

[WinDirStat.zip](https://github.com/user-attachments/files/17708701/WinDirStat.zip)

**Comment by philumax** [comment]
I'm going to eat, go to bed and I'll try it tonight, I can't before, I have to refuel!Bye !envoyé : 11 novembre 2024 à 23:30de : Bryan Berns ***@***.***>à : windirstat/windirstat ***@***.***>cc : philumax ***@***.***>, Author ***@***.***>objet : Re: [windirstat/windirstat] It doesn't work anymore! Help! (WindirStat) (Issue #132) Thanks for sending the dump. Can you see if this version as the same issue:WinDirStat.zip—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by NoMoreFood** [comment]
@philumax Any luck?

**Comment by philumax** [comment]
Hello.
Sorry for the delay, I was busy and it took a while.
I tried the X64 and the X32: the X64 crashes, not the X32.
There must be a reason!
See you later.

**Comment by NoMoreFood** [comment]
By "crashes" to you means freezes / hangs?

**Comment by philumax** [comment]
Freezes !
The droplets are activated and it freezes. I press with the mouse pointer and there, Windows answers me: Windirstat does not respond. I press the cross, Windows asks me if I want to end the program: I say yes. Windows answers: Windows sends something to report the crash and it closes.

**Comment by NoMoreFood** [comment]
@philumax  Can you see if this release changes the behavior at all? 
https://github.com/windirstat/windirstat/releases/tag/beta/v2.1.0/2024-11-30

**Comment by philumax** [comment]
It crashes right after the search finishes.
![2024-12-01_06h47_38](https://github.com/user-attachments/assets/f19290f7-a78b-4512-a32f-856d651b6ba7)
![2024-12-01_06h51_04](https://github.com/user-attachments/assets/58a6c2a9-cf8f-494b-9bb6-2da848870cd3)
![2024-12-01_06h52_58](https://github.com/user-attachments/assets/61ca92c0-c044-4daa-97d2-994b1f018b86)
See you later!

**Comment by NoMoreFood** [comment]
@philumax Can you do another dump file for me?

**Comment by NoMoreFood** [comment]
@philumax Got the dump file.  I see where it's freezing - basically when it's trying to grab the icons for the extension list. Try this version.  If this doesn't work, I'll change the code so the affected call won't operate in the main thread.

[WinDirStat.zip](https://github.com/user-attachments/files/17970145/WinDirStat.zip)

**Comment by philumax** [comment]
Seen !

**Comment by philumax** [comment]
![2024-12-02_08h50_26](https://github.com/user-attachments/assets/55619af1-cf02-4f15-8fde-efa7374dd7f6)
![2024-12-02_08h52_59](https://github.com/user-attachments/assets/31eea234-1e90-400f-8dd0-174dac5714ab)

**Comment by philumax** [comment]
Quick Question: What is the difference between the "sequoia" view and the KDirStat view?
It looks like the big files are on the left and the small ones on the right.

**Comment by NoMoreFood** [comment]
@philumax Yeah, as far as I know it's just a slightly different visualization of the data inspired by how the authors of KDirStat and SequoiaView decided to display data.

**Comment by NoMoreFood** [comment]
@philumax This issue is getting a bit lengthy and we addressed the issue for at least two others, I'm going to close it. I ask that you could rebaseline with 2.1.1 (https://github.com/windirstat/windirstat/releases/tag/release/v2.1.1) and open a new issue if this is still present.  Thanks!
