### ISSUE TITLE
Feature Request: Disable automatic column resize feature

### ISSUE THREAD

**Issue by kaala** [windirstat/windirstat#134]
When I expand into subfolders, the column will automatically expand size to show the filename.
This will make the column too wide if there are long filename inside, and collapse the folder will no automatically shrink the column size.
This is not convenience, please improve this.
![image](https://github.com/user-attachments/assets/5f481916-adea-4f87-b5ab-381587651e3d)

**Comment by NoMoreFood** [comment]
Might be willing to entertain this.  What would you propose?  An option to disable expansion or an option to option to automatically shrink on collapse?  Curious on others' thoughts here.

**Comment by kaala** [comment]
I personally prefer disable auto expansion.

**Comment by NoMoreFood** [comment]
Can you try this version?  Should be a new option on the General settings page.  You can still auto-size by double-clicking the column header divider.

[WinDirStat.zip](https://github.com/user-attachments/files/17687079/WinDirStat.zip)

**Comment by kaala** [comment]
Thank you, I tried it, and it looks great.

**Comment by NoMoreFood** [comment]
Released with https://github.com/windirstat/windirstat/releases/tag/release/v2.1.1
