### ISSUE TITLE
Beta 21.0.890 (2024-11-06) - No Deletion Progress

### ISSUE THREAD

**Issue by jamesaepp** [windirstat/windirstat#135]
Windows 11 23H2

I don't necessarily have repro steps here, just reporting in case anyone else has the same. Didn't see a similar issue open.

Using the beta against an SMB share mapped as a drive. Had a folder highlighted in the nav/file pane and used the red bin icon in the toolbar to start a deletion. The following unexpected behavior occurred:

- No progress bar/window for the deletion
- WinDirStat went into not responding for maybe a minute, then returned

As far as I can tell based on looking at the original directory and from watching task manager during the time of the deletion, some files were deleted from the folder, but not the entire folder. I feel like the file deletion process crashed.

**Comment by NoMoreFood** [comment]
Do you know if the files that it left could actually be deleted (i.e., not in-use)?

**Comment by jamesaepp** [comment]
I was able to delete all the files via explorer completely normally - no funny business, no UAC prompts, just worked.

**Comment by NoMoreFood** [comment]
For both the manual deletion and the WinDirStat deletion, was it to the Recycle Bin?

**Comment by jamesaepp** [comment]
Nope, permanent both times.

**Comment by NoMoreFood** [comment]
Alright, thanks.  I know we need to improve the UI experience during permanent deletion, but I have yet to experience a scenario where it aborted deletion.  I will see if I can reproduce what you are describing on an SMB path.

**Comment by rdp** [comment]
Yeah just ran into this as well, basically create a folder, have a cmd cd'd to it, try "permanent delete" or to recycle bin, it just does the refresh and ignores that it just failed, 1.x seemed to give a prompt "this folder is in use", cheers!

**Comment by jamesaepp** [comment]
FWIW I'm _pretty sure_ I had all other handles/use of the original folder I was deleting closed with the exception of WinDirStat itself but I could be wrong.

**Comment by NoMoreFood** [comment]
Released with https://github.com/windirstat/windirstat/releases/tag/release/v2.1.1
