### ISSUE TITLE
Shortcut to sendto does not send path

### ISSUE THREAD

**Issue by Antonimo-Dev** [windirstat/windirstat#136]
WinDirStat 2.0.3

I have upgraded from the very old previous WinDirStat. I always used to have a shortcut in shell:sendto to send the path to WinDirStat for analysis.

Is there a chance this behaviour can be included in a future release of the shiny new version of WDS?

**Comment by NoMoreFood** [comment]
The new version has a context menu entry that shows up on drives and folders.  Doesn't that accomplish the same goal?

![image](https://github.com/user-attachments/assets/231921c1-c005-44ea-8052-5fc4ce4bf25a)

**Comment by Antonimo-Dev** [comment]
Yes, that's good. I had the portable version so I was using the shell:sendto folder to add the menu item.
