### ISSUE TITLE
Mouse over not sticking

### ISSUE THREAD

**Issue by FuzzyRick** [windirstat/windirstat#138]
Hi

When the graphical view is displayed, it is essential to be able to run the mouse over the files and see the filename.  In version 2 the filename appears for a brief second and then the status bar returns to saying ready.  So it's nearly impossible to actually see the filename without clicking on it.
This makes version 2 totally useless to me, which is a pitty cause i can see a lot of improvements.  Hopefully this can be fixed.

**Comment by NoMoreFood** [comment]
@FuzzyRick Yes, this is fixed the beta release which I hope will be out in the next few weeks.  Please test it out.  Thanks!

https://github.com/windirstat/windirstat/releases/tag/beta%2Fv2.1.0%2F2024-11-06

**Comment by FuzzyRick** [comment]
Yeah thanks, I found the beta shortly after posting.  All good

**Comment by NoMoreFood** [comment]
Released with https://github.com/windirstat/windirstat/releases/tag/release/v2.1.1
