### ISSUE TITLE
New Time calculation inaccurate

### ISSUE THREAD

**Issue by AartBluestoke** [windirstat/windirstat#14]
runtime time is only accurately reported for 1 thread.
I've seen it both faster and slower (here is a slower - clearly you can't do a refresh in only 1 second)

here is a run with 6 seconds wall clock, 49 seconds runtime reported
![image](https://github.com/windirstat/windirstat/assets/1892829/bdab470b-252d-484f-8b17-ce2a2200c96c)

here is a refresh of an existing run that reports completion in only 1 second (it took the normal time visually)
![image](https://github.com/windirstat/windirstat/assets/1892829/de884546-a0a2-4255-93c7-60d1bd565442)

**Comment by NoMoreFood** [comment]
Yup, this is on the to-do list.   It's a consequence of multi-threading.  Do you find the total time spent helpful?   I'm questioning whether it might be just right thing to remove it altogether.

Curious... on your drives... if you run it, close it, and run it again.  How long does it take to run?

**Comment by AartBluestoke** [comment]
10 seconds with 4 threads, down to 5 seconds with 16 threads - the 6 seconds above was with ~8 threads selected.
my drives are 2x https://www.crucial.com/ssd/p5-plus/ct2000p5pssd8 (2TB) 
cpu is 12900H
i'm on windows 11.

**Comment by AartBluestoke** [comment]
as another time point for execution speed https://locate32.cogit.net/ (https://github.com/Locate32/Locate32) appears to be able to index my system single-threaded in ~20 seconds.

**Comment by assarbad** [comment]
I find the wall clock time most useful. Thread times can be intriguing for the tech-savvy, but do they really play a role?

@AartBluestoke did you also empty the lookaside cache (or reboot) between your test runs? Otherwise any subsequent tests will always be faster, given a machine that isn't under a lot of cache stress. The RAMMap utility from Sysinternals/Microsoft offers the option to empty said caches.

**Comment by NoMoreFood** [comment]
Yeah, I should have been clearer -- I don't actually think the cumulative thread time is useful -- it was just a consequence of the multithreading change.  Algorithmically, I'll have to think hard about we can accurately track wall clock time for each branch at each level when there could be multiple threads beneath it starting and stopping at different times while not harming performance or eating up extra memory.

**Comment by AartBluestoke** [comment]
> @AartBluestoke did you also empty the lookaside cache (or reboot) between your test runs? 
- no - i'll do another run now ( i recently rebooted) - it took 10 to 11 seconds (my hand-timing was poor, and there is a pause between the completion of the sweep and the display of the treemap (i try to aim at the end of the treemap display)
- 
![image](https://github.com/windirstat/windirstat/assets/1892829/f8511f3e-b6d2-4147-a92d-0c5291bb4a76)

**Comment by AartBluestoke** [comment]
an immediate re-execution was about half the time (currently set to 10 threads)
![image](https://github.com/windirstat/windirstat/assets/1892829/75e6062f-640a-4503-94e8-51d14d043f07)

**Comment by NoMoreFood** [comment]
@AartBluestoke Can you try the latest commits?

**Comment by AartBluestoke** [comment]
new behaver - time is working, but scan is broken - i've installed google drive, and this appears to have caused windirstat to hang - it just spins with this screen, gradually increasing ram ... 
![image](https://github.com/windirstat/windirstat/assets/1892829/5c9d21f2-49d9-44b6-aafd-f64c5fac2e14)

**Comment by AartBluestoke** [comment]
edit: not google drive - i closed it and saw the same behavior. 
![Uploading image.png…]()

**Comment by NoMoreFood** [comment]
@AartBluestoke Thanks I'll take a look. Does it occur if you target a single folder?

**Comment by NoMoreFood** [comment]
Actually I think I see the problem.  I committed a small change that I think should address the behavior.  I had rearranged a few things for the timing and injected a bug along the way.
