### ISSUE TITLE
Minor translation fixes

### ISSUE THREAD

**Issue by tferrerm** [windirstat/windirstat#144]
Many translations for `IDS_EXTENSION_MISSING` are wrong. Please change to the following suggested ones, or at least similar ones:

de:
Change `IDS_EXTENSION_MISSING` to `Ohne Dateityp`

es:
Change `IDS_EXTENSION_MISSING` to `Sin Extensión`

fr:
Change `IDS_EXTENSION_MISSING` to `Sans Extension`

it:
Change `IDS_EXTENSION_MISSING` to `Senza Estensione`

nl:
Change `IDS_EXTENSION_MISSING` to `Zonder Extensie`

pl:
Change `IDS_EXTENSION_MISSING` to `Bez Rozszerzenia`

For the rest of the languages it either seemed fine or I simply don't know how it should be.
Great piece of software BTW, love it :)

**Comment by NoMoreFood** [comment]
@tferrerm Thanks for the help! Can you confirm they are updated in this release: https://github.com/windirstat/windirstat/releases/tag/beta/v2.1.0/2024-12-01

**Comment by tferrerm** [comment]
@NoMoreFood I just confirmed that they are updated in Spanish and Italian, so I assume the rest of the translations have been changed as well
![Captura de pantalla 2024-12-02 101800](https://github.com/user-attachments/assets/933a9aaf-a78c-4b5d-b430-8b2d4eaa88ce)
![Captura de pantalla 2024-12-02 101916](https://github.com/user-attachments/assets/3bcf5954-c3b2-4dcb-bed5-7e9420e7586e)

**Comment by NoMoreFood** [comment]
Released with https://github.com/windirstat/windirstat/releases/tag/release/v2.1.1
