### ISSUE TITLE
Could you please add an ability to exclude folders?

### ISSUE THREAD

**Issue by AxlMoscow** [windirstat/windirstat#148]
Hello!
You have created an incredible, very useful program and I am very grateful to you for it.
But it really lacks the ability to exclude folders.
That is, after a folder or disk has been scanned and displayed, it often happens that the graph displays also important and necessary folders that you don't want to delete but which take up a lot of space on the screen and interfere with the analysis of other folders.
If it were possible to exclude these folders, it would greatly improve the efficiency of working with the program.
Thank you very much for your attention to my proposal.
Have a great day!

**Comment by NoMoreFood** [comment]
@AxlMoscow 

We have a beta version that supports exclusion that will be released soon.  Please try it out:

https://github.com/windirstat/windirstat/releases/tag/beta/v2.1.0/2024-12-07

**Comment by NoMoreFood** [comment]
Released with https://github.com/windirstat/windirstat/releases/tag/release/v2.1.1
