### ISSUE TITLE
reported disk and file size 10x what it should be

### ISSUE THREAD

**Issue by AartBluestoke** [windirstat/windirstat#15]
i've ~2TB drives, reported as 18TB in scan, and used space is also "funny"
![image](https://github.com/windirstat/windirstat/assets/1892829/5fa6f78e-f544-4ddd-bead-c4b36356b142)

also, not the 800% disk usage ...

**Comment by AartBluestoke** [comment]
this also affects the reported ram usage (a run isn't using 4GB, its using 400mb - incidentally, half what the previous version used to use):
![image](https://github.com/windirstat/windirstat/assets/1892829/12c14632-3e73-4c0c-8fd3-91629fab4202)

**Comment by NoMoreFood** [comment]
Thank you for testing.   That is very, very odd since both the total drive space and the memory usage are simple API calls into Windows.   Is this using a 32-bit build or a 64-bit build?

**Comment by NoMoreFood** [comment]
@AartBluestoke Alright, I think I understand the issue. What locale are you in? I think the problem is the decimal separator character is rendering so instead of "1.8", you're seeing "18". I recently reworked and it's very possible I have a regression in the initial locale processing.

**Comment by AartBluestoke** [comment]
HKEY\Software\WinDirStat\WinDirStat\persistence\Language 
![image](https://github.com/windirstat/windirstat/assets/1892829/9ad777cc-4e70-4a06-8643-c4588eadeb7d)

**Comment by NoMoreFood** [comment]
Yup, my theory is correct.  I will add some code to guard against that.  Thanks!

**Comment by NoMoreFood** [comment]
@AartBluestoke Please try my latest commit if you have a chance please.

**Comment by AartBluestoke** [comment]
@NoMoreFood latest codebase works, initial screen, reported size, and ram usage are now 'sane' :)
![image](https://github.com/windirstat/windirstat/assets/1892829/dc4c4383-5b81-43e8-a6a1-2fdc246cf4e4)
