### ISSUE TITLE
windrstat y sus funcionalidad

### ISSUE THREAD

**Issue by FenixxAngel** [windirstat/windirstat#157]
es una excelente aplicacion que realmente ayuda a las personas con poca organizacion a poder tener un poco de orden en todos sus archivos, ademas de ser automata. y los desordenados tambien lo somos por eso es una excelente aplicacion para todo tipo de personas. s bien ustedes se pueden imaginar si ayuda a una persona con desorden lo que va a hacer con las personas que mantienen su organizacion hasta para ir al baño.
felicidades.

**Comment by FenixxAngel** [comment]
yo no la estaba buscando lo que es una realidad que el momento que yo abri la red no fue para buscar quien me ayudara, yo estaba buscando alguna funcion para poder eliminar todo lo que tenia duplicaco y que yo sabia que estaba ahi. pero no sabia como buscarlo.

**Comment by NoMoreFood** [comment]
Google Translate isn't helping me much here.  Can I native speaker help translate what this is asking?

**Comment by NoMoreFood** [comment]
Closing until we get better clarity on this request.
