### ISSUE TITLE
Crash while deleting permenantly

### ISSUE THREAD

**Issue by linuxgurugamer** [windirstat/windirstat#158]
Version:  Beta 2.1.2 (2024-12-18)

I selected a number of files (using the ctrl-click) in the duplicate files window (from a number of different files), then right-clicked and selected Delete Permanently.  Program just exited.
Additional testing showed that it crashed after deleting the 2nd of multiple files

Selecting Delete to Recycle had similar issues.

Not sure if relevent, but this was on my Google Drive 

I did similiar tests on other drives, and at multiple times saw the same issue

**Comment by NoMoreFood** [comment]
@linuxgurugamer Can you see if you can repro with 2024-12-20?  I already addressed some issues with selecting/deleting/highlight out of duplicates area.

**Comment by linuxgurugamer** [comment]
Working with 2024-12-20
Also, the X to close also worked.
Thanks
