### ISSUE TITLE
Add Git revision retrieval back, to replace the one we had for Mercurial

### ISSUE THREAD

**Issue by assarbad** [windirstat/windirstat#17]
This relates to #16 ... I have something in store already, but need to make it work with WDS's code base.

**Comment by assarbad** [comment]
Fixed by 774efdf8ff57ec452d4ac654612a0c325553b0f6

**Comment by assarbad** [comment]
@NoMoreFood: this relies on `git.exe` being there. Seeing that some people don't use traditional Git at all but only some integration of libgit2, do you think this is an alright assumption?

If `git.exe` isn't found it should gracefully handle it and the define `GIT_COMMIT` simply won't be available to `rc.exe` or `cl.exe`.

**Comment by NoMoreFood** [comment]
I think the presence of git.exe is a perfectly acceptable assumption.
