### ISSUE TITLE
Can the homepage be updated to say it works with Windows 10 and Windows 11?

### ISSUE THREAD

**Issue by imthenachoman** [windirstat/windirstat#21]
I am trying to use WinDirStat in a high secure environment. The security team can't approve it because https://windirstat.net/download.html does not list Windows 10/11 under compatibility.

I know it works on Windows 10/11 but it needs to be listed there.

Is that something someone can help make happen?

BTW, I love WinDirStat. One of the most useful programs out there.

**Comment by NoMoreFood** [comment]
@assarbad With one or two minor exceptions, it seems to be fully compatible with Windows 11.  I think it's fair to add Windows 11 to the list of supported platforms.  Thoughts?

**Comment by NoMoreFood** [comment]
Website has been updated
