### ISSUE TITLE
Using the keyboard LEFT/RIGHT keys does not collapse/expand nodes in the tree view

### ISSUE THREAD

**Issue by RobertK66** [windirstat/windirstat#22]
I am using this Software since ... (hmmm ages!). 
I have version "1.1.12 80(Unicode)" installed under Windows 11 23H2 22631.3155 and it really does fit its purpose.

I came around this repos - downloaded the sources into my VS 2022 Pro 17.8.7 - build and debug worked on first try! - congrats to your clean repos!

Debugging from VS showed the behavior described in the title. Up and Down keys are working and select the rows of the tree. But other than in the installed version the LEFT/RIGHT keys do not show any reaction.

I poked around in the source code but I have little experience with C++ projects and 0-experience with mfc 😄.  Referring to #6 I am also happy to help with testing and playing around with this version (you plan to release a new one here?)

**Comment by NoMoreFood** [comment]
We will take a look.  I am hoping April for the next release, but that could change.  When it is released, it will minimally be updated on the website, and I suspect we'll release in this repo as well.

**Comment by RobertK66** [comment]
ok adding
```
void CTreeListControl::OnKeyDown(UINT nChar, UINT nRepCnt, UINT nFlags)
{
    if (nChar == VK_RIGHT) {
        const auto& items = GetAllSelected();
        if (items.size() == 1) {
            int i = FindTreeItem(items[0]);
            if (!GetItem(i)->IsExpanded())
            {
                ExpandItem(i);
            }
        }
    }
    else if (nChar == VK_LEFT) {
        const auto& items = GetAllSelected();
        if (items.size() == 1) {
            int i = FindTreeItem(items[0]);
            if (GetItem(i)->IsExpanded())
            {
                CollapseItem(i);
            }
        }
    }
    COwnerDrawnListControl::OnKeyDown(nChar, nRepCnt, nFlags);
}
```
seems to do the trick. In 1.1.12 the VK_LEFT also does something else like 'jumping to the parent node'(or so?). I am not sure how to do this here but why and where was this functionality lost? Ist the code here a complete Re-Write of the previous release?

**Comment by NoMoreFood** [comment]
Yes, you were exactly correct. I committed a changed based on your findings.

**Comment by RobertK66** [comment]
Excuse my pickiness here, but maybe we should add a 'return;' when the keystrokes 'are used up'. Current code additionally to expanding/collapsing does a little scroll step if there is a horizontal scroll bar visible....

**Comment by NoMoreFood** [comment]
@RobertK66 I will take a look at that.

**Comment by NoMoreFood** [comment]
Can you confirm the latest release addresses this?

https://github.com/windirstat/windirstat-next/releases

**Comment by RobertK66** [comment]
yes, its ok now

**Comment by PEERSOFTdev** [comment]
I would be very grateful for the Left Cursor key to really select (focus) the parent's item so that I could press it again to collapse it, like v1.1.12 did. For screen reader users, it is quite difficult to find the parent when you are viewing a large subtree and get lost where you are.

**Comment by RobertK66** [comment]
yes this was behavior from before https://github.com/windirstat/windirstat/commit/2c58b5dec1b2c83936594cc00e0776f1c5b36014. As I found this, i was not sure how the original code should be transported because this refactorig did many changes with the selection of nodes. I tried this now with:

```
 else if (nChar == VK_LEFT) {
    const bool shift = (0x8000 & ::GetKeyState(VK_SHIFT)) != 0;
    const bool control = (0x8000 & ::GetKeyState(VK_CONTROL)) != 0;

    const auto& items = GetAllSelected();
    if (items.size() == 1) {
        if (items[0]->IsExpanded())
        {
            int i = FindTreeItem(items[0]);
            CollapseItem(i);
        } else if (items[0]->GetParent() != nullptr && !control && !shift)
        {
            //SelectSingleItem(items[0]->GetParent());    !!! not there any longer !!!!
            SelectItem(items[0]->GetParent(),true, true);
        }
        //else !!! not sure if i really want this !? 
        //{
        //    ::MessageBeep(0);
        //}
    }
    return;
} 
...
```

it seems to work for the left key, but I think it would be nice if @NoMoreFood could give a short glance over all the other key handlers which where abandoned by this refactoring. There was code available for:  VK_UP, VK_DOWN, VK_PRIOR, VK_NEXT. I am not sure how this relates to the other changes done then....
