### ISSUE TITLE
Enhancement Request - Filter / Multi-Select / Disable Auto Refresh on Delete

### ISSUE THREAD

**Issue by Gerbilnut** [windirstat/windirstat#25]
I typically use WinDirStat to find and delete a large amount of empty or small directories.  This has become incredibly tedious by some of the programs limitations.  A list of proposed enhancements are below.

- Provide a filter option to allow limiting the directory list to items below a certain size or with less than a specified number of files
- Enable the ability to hold Ctrl while clicking to select multiple items for deletion
- Provide the ability to disable the directory tree completely refreshing and starting at the parent directory when a child directory is deleted.

**Comment by NoMoreFood** [comment]
"Provide the ability to disable the directory tree completely refreshing and starting at the parent directory when a child directory is deleted." Can you elaborate on this a little more?

**Comment by NoMoreFood** [comment]
@Gerbilnut - this release is a little smarter about deleting multiple items:

https://github.com/windirstat/windirstat-next/releases/tag/Release_1_3_0_2024_03_25

I would appreciate any feedback.

**Comment by Gerbilnut** [comment]
@NoMoreFood The new release does a much better job of handling multiple file deletions.  It addressed the second and third items on my list above which makes the first irrelevant now. Thank you!
