### ISSUE TITLE
Feature request: Implement DPI awareness

### ISSUE THREAD

**Issue by vlakoff** [windirstat/windirstat#26]
First of all, thank you for pursuing the development of WinDirStat. Even though more recent alternatives exist, many people prefer to use WinDirStat, simply because it's the one that provides the most helpful visualizations.

So, my OS is configured with 125 % font scaling, and because of this, the entire interface of WinDirStat is blurred. It is because the application is completely DPI-unaware currently, thus Windows scales it using the bitmap-stretching fallback method.

References:

- [High DPI Desktop Application Development on Windows](https://learn.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows) on learn.microsoft.com
- [High DPI Scaling Improvements for Desktop Applications and “Mixed Mode” DPI Scaling in the Windows 10 Anniversary Update (1607)](https://blogs.windows.com/windowsdeveloper/2016/10/24/high-dpi-scaling-improvements-for-desktop-applications-and-mixed-mode-dpi-scaling-in-the-windows-10-anniversary-update/) on blogs.windows.com
- [High-DPI Scaling Improvements for Desktop Applications in the Windows 10 Creators Update (1703)](https://blogs.windows.com/windowsdeveloper/2017/04/04/high-dpi-scaling-improvements-desktop-applications-windows-10-creators-update/) on blogs.windows.com
- [C++ Windows API - How to retrieve font scaling percentage on Windows 10](https://stackoverflow.com/questions/66161063/c-windows-api-how-to-retrieve-font-scaling-percentage-on-windows-10) on stackoverflow.com

If applicable, I would suggest to use the latest API offered, "Per-Monitor V2". Windows 10 Creators Update (1703) dates back from March 2017 already.

**Comment by NoMoreFood** [comment]
@vlakoff I'm already working on this in a local branch, but I always struggle to see (literally) this blurriness that some people report. You mentioned the 125%.  Are there any other factors that play into seeing the blurriness?

**Comment by vlakoff** [comment]
Here is what I have with 150% font scaling (you may compare with the text in the title bar, which is clear):
![WinDirStat - font scaling 150%](https://github.com/windirstat/windirstat/assets/544424/aeab1685-bed6-4b8b-a605-f91c73fb9c42)

And with 125% font scaling:
![WinDirStat - font scaling 125%](https://github.com/windirstat/windirstat/assets/544424/c03e80cb-7539-4881-a19b-bd3ce61618bb)

Now compare with 100% font, where everything is sharp and clear:
![WinDirStat - font scaling 100%](https://github.com/windirstat/windirstat/assets/544424/dfd6ad92-c472-48b7-bbc2-c60005e2c1a0)

Note: if viewing this page with font scaling enabled in the OS, the browser resizes all contents, including the images above. Even if the issue should already be noticeable, you may want to save the images and open them with an external image editor, so that you see them with the real pixel ratio.

**Comment by NoMoreFood** [comment]
@vlakoff 

Thank you.  After tinkering with updating all the various owner drawn elements that are not automatically DPI aware, I tried out the new-ish automatic "gdiScaling" option and was pretty satisfied with that.  Can you give the latest release a try:

https://github.com/windirstat/windirstat-next/releases

**Comment by vlakoff** [comment]
It is much better, indeed.

I am very experienced at spotting such "pixel level" issues, so I'm still able to see that some resizing occurs, but the result is so clear that it's very close to a "native" font size (without any resizing), and I guess most people wouldn't tell the difference.

The change seems to be very simple ([82413d9](https://github.com/windirstat/windirstat/commit/82413d9e7783f29563447e9fec64fbe5886da350)), and I suppose there is no way to do it even better actually. Any font scaling percentage can be used actually, not only the predefined 125%, etc. values, so we can't pick hard font size values like 12, 14, etc. (BTW, the maximum precision is one decimal, e.g. 12.4). Thus, dynamic font resizing do have to be used.

It seems to be the best that can be achieved here, and thankfully the result is satisfying, in particular considering it is a GDI application.

Note I haven't tested things like multi-monitor setup, or changing font scaling while the program is open. But my guess is that it should be fine.

This article might be of interest: [Improving the high-DPI experience in GDI based Desktop Apps](https://blogs.windows.com/windowsdeveloper/2017/05/19/improving-high-dpi-experience-gdi-based-desktop-apps/)
