### ISSUE TITLE
WinDirStat Alpha Build (2024-03-17) crashed when deleting multiple folders (bypassing Recycle bin)

### ISSUE THREAD

**Issue by vittoso** [windirstat/windirstat#27]
Hello,
I was testing https://github.com/windirstat/windirstat-next/releases/tag/Release_1_3_0_2024_03_17 x64 (not elevated).
I had an application crash (exception 0xc0000409 wihich I believe is stack butter overrun) when deleting multiple folders bypassing Windows recycle bin. 

Here's what I did:
![WinDirStatCrash_20240324](https://github.com/windirstat/windirstat/assets/1496592/e99c66e6-df98-4097-a95f-643a1f1593f8)

![Cattura](https://github.com/windirstat/windirstat/assets/1496592/9164dd6f-421d-4069-9fa7-ad80d77c82b8)

Here's a procdump -ma dump that I managed to capture, I hope it's useful:  [dump](https://1drv.ms/u/s!Al6awteDkZjcm0nhtVCe1QYY2NTh?e=2oBlw1)

**Comment by NoMoreFood** [comment]
Did you find the issue to be repeatable?

**Comment by vittoso** [comment]
> Did you find the issue to be repeatable?

Absolutely, repeated 3 times, I took the dump on the fourth.

**Comment by NoMoreFood** [comment]
I reproduced it one time, but I could not reproduce it a second time and, unfortunately, I did not save the debug symbol files from that alpha build.  I will not make that mistake in the future.  Can you see if you can reproduce the issue with this file?

[WinDirStat64D.zip](https://github.com/windirstat/windirstat/files/14737073/WinDirStat64D.zip)

**Comment by NoMoreFood** [comment]
@vittoso Try this build please:

https://github.com/windirstat/windirstat-next/releases/tag/Release_1_3_0_2024_03_25

**Comment by vittoso** [comment]
> @vittoso Try this build please:
> 
> https://github.com/windirstat/windirstat-next/releases/tag/Release_1_3_0_2024_03_25

I works fine in this version. The only thing is that sometimes it shows the "non responding" text in the application title, might be some blocking on the UI thread while recalculating. But definitely it doesn't crash any longer, thanks!
