### ISSUE TITLE
WinDirStat Alpha 1.3.0-2024-03-25: putting a lang-XX.txt file in the same folder of the executable does not override the toolbar tooltips

### ISSUE THREAD

**Issue by vittoso** [windirstat/windirstat#29]
Hi,
I am trying to refresh and harmonize some italian translations and I found out that putting a lang_it.txt file in the same folder of the WinDirStat64.exe correctly override the menu strings but the tooltips of the toolbar below the menu are not overriden.

![Untitled](https://github.com/windirstat/windirstat/assets/1496592/445c66c6-f18f-4115-bf4d-a20d7631adfa)

**Comment by vittoso** [comment]
> @vittoso Can you see if you have the same problem with this latest release?
> 
> https://github.com/windirstat/windirstat-next/releases
> 
> This release should also contain the pull request you submitted. Thanks!

Hi,
I confirm that this bug is fixed in the release you gave me. Thanks!

However it seems that the IDS_FILE_SELECT is still:
IDS_FILE_SELECT=Apre una raccolta di unità.\nApri
instead of what I suggested
IDS_FILE_SELECT=Seleziona unità.\nApri

**Comment by NoMoreFood** [comment]
That was my mistake; it was accidently dropped when resolving a merge.  I committed the change to master and it'll be in the next binaries I build.  Thanks!

**Comment by NoMoreFood** [comment]
Should be in the latest: https://github.com/windirstat/windirstat-next/releases

**Comment by vittoso** [comment]
Latest versione seems fine, thank you
