### ISSUE TITLE
UI freeze if folder is expanded while scanning

### ISSUE THREAD

**Issue by jhv2017kam** [windirstat/windirstat#31]
If you try to open a folder while scanning is ongoing the UI freeze
i.e. use mouse to clicking small box with plus while yellow Pacmans are moving from side to side

**Comment by NoMoreFood** [comment]
@jhv2017kam Which version are you using?

**Comment by NoMoreFood** [comment]
@jhv2017kam Can you see if you have the same or similar behavior with this release:

https://github.com/windirstat/windirstat-next/releases/tag/Release_1_3_0_2024_03_26

**Comment by jhv2017kam** [comment]
that version works fine
