### ISSUE TITLE
Constant CPU usage, worsening over time, and UI becoming unresponsive

### ISSUE THREAD

**Issue by vlakoff** [windirstat/windirstat#32]
I noticed that as soon as WinDirStat is opened, it constantly uses about 4 % CPU, and it worsens over time.

For instance, after a few minutes it has reached a constant 12 % CPU usage. More problematic, the UI has become near to unresponsive, and it even affects the rest of Windows, where I can notice some delays happening (even though the computer is multi-core, and WinDirStat doesn't take 100 % CPU).

You have guessed it, it seems that a leak has been introduced somewhere…

**Comment by vlakoff** [comment]
Trying to pinpoint the cause, all releases currently listed on https://github.com/windirstat/windirstat-next/releases (from 2024‑02‑11 to 2024‑03‑29) have the issue.

It's surprising how it can affect the whole Windows environment. Open about 10 instances of WinDirStat, and see how the computer becomes unresponsive.

The original WinDirStat is unaffected, it stays at a nice 0 % CPU usage, and dozens of instances can be opened without any problem.

**Comment by NoMoreFood** [comment]
Sounds like a run-away thread.  Do you have to actually start a scan to see this behavior?

**Comment by vlakoff** [comment]
No, just starting the application is sufficient.

**Comment by NoMoreFood** [comment]
That is very interesting - I am not seeing this behavior.  If you close the drive selection dialog (without doing anything), does the problem go away?  There is some threading that goes on at the drive selection dialog, but then the rest of the threads are only created if you run a scan.  What version OS and what CPU do you have?

If I can't infer what's going on, I may have to have you run a debug version that we can use to create a memory dump in Task Manager.

**Comment by vlakoff** [comment]
The problem doesn't disappear if I close the drive selection dialog.

So, you can open, let's say a dozen of instances, and nothing happens for you? Maybe try opening more, or leaving them open for a bit.
How much CPU the instances use in your task manager? Not even a few percents? (expected should really be 0%, at most something like 0.1%).

OS: Windows 10 Pro x64 22H2 (issue happens on both 32-bit and 64-bit builds of WinDirStat)
CPU: i7-1185G7 (mobile)

**Comment by NoMoreFood** [comment]
No, I don't see it go above 0%.  It must be the UI thread causing the issues based on what you're describing.  My computer is faster than yours, but not enough to account for the difference. I have an older laptop I can try it on later today.

Can you try this executable?  It lowers one of the UI timers that I had set to fire frequently.  It's not a version I'd recommend using, but it will help me determine if that's where the issue is.

[WinDirStat64-ReducedTimer.zip](https://github.com/windirstat/windirstat/files/14811965/WinDirStat64-ReducedTimer.zip)

**Comment by vlakoff** [comment]
Things are much better on this build. CPU is around 1%, and if I start like a dozen instances, there is barely no side-effect on Windows. The issue is still present, but drastically reduced.

I don't know if it may come into play, but the laptop doesn't have dedicated GPU, it's running on the integrated Iris Xe graphics. A pretty good IGP, but still an IGP. (And just to confirm: the drivers are up-to-date.)

**Comment by vlakoff** [comment]
Ah, and I'm running 4K resolution on this IGP, lol.

But this app is really the first one on which I encounter such an issue.

**Comment by NoMoreFood** [comment]
Yeah, that build was basically making the UI update timer run 10x slower.  The only reason it really runs that fast is for the Pacman graphic that I know everyone loves.

**Comment by NoMoreFood** [comment]
@vlakoff Can you see if the latest release is better?  Made some adjustments which hopefully should mitigate the reported issue and also speed up scan times slightly:

https://github.com/windirstat/windirstat-next/releases

**Comment by vlakoff** [comment]
It's much better than on previous pre-releases.

I have opened about 30 instances, CPU usage of each instance is below 1%, with spikes to about 1.4%.
The rest of the Windows environment is still affected, but it's not very noticeable (for example, moving windows of other apps gets some stuttering), whereas previously the computer would have become unusuable with so many instances open.

Thus, the issue is still "present", but mitigated a lot, to a point it can't be noticed. I don't know if technically it would be possible to fix it even further (after all, it's normal that the instance has some work to do).

**Comment by NoMoreFood** [comment]
Thank you for confirming.  For the near term, I'd like to consider this one as complete for the moment, and I will continue to look for ways to further optimize it once the MFC / profiler bug is fixed (which I'm hoping comes in the 17.10 feature release of Visual Studio 2022).
