### ISSUE TITLE
Crash when deleting already deleted folder

### ISSUE THREAD

**Issue by tron2k** [windirstat/windirstat#33]
Version: 1.3.0-2024-03-31

When I delete an Folder in WinDirStat that was already deleted over File Explorer WinDirStat crashes.

**Comment by NoMoreFood** [comment]
Can you confirm the latest release addresses this?

https://github.com/windirstat/windirstat-next/releases

**Comment by tron2k** [comment]
thank you, it is fixed.

**Comment by tron2k** [comment]
thank you, it is fixed.
