### ISSUE TITLE
How can User restore the Delete Warning Option?

### ISSUE THREAD

**Issue by tron2k** [windirstat/windirstat#36]
I can not find a Option to active the Delete Warning Option after it was disabled. The only way I find is changing the registry key.

**Comment by NoMoreFood** [comment]
Good idea.

**Comment by NoMoreFood** [comment]
@tron2k Can you please check out the latest release for this? 

https://github.com/windirstat/windirstat-next/releases

**Comment by tron2k** [comment]
> @tron2k Can you please check out the latest release for this?
> 
> https://github.com/windirstat/windirstat-next/releases

@NoMoreFood 
The Build 2024-04-04 does not have a Exe Zip file.

**Comment by NoMoreFood** [comment]
@tron2k Sorry, should be there now.
