### ISSUE TITLE
WinDirStat-1.3.0-2024-03-31 x64 crashes if deleting a file that was deleted in the meantime

### ISSUE THREAD

**Issue by vittoso** [windirstat/windirstat#37]
Hi,
I found out a WinDirState crash with version 1.3.0-2024-03-31 (x64) with the following repro steps:
1. Launch a scan in WinDirStat
2. Select a file in WinDirStat
3. Open explorer.exe and delete the same file selected in WinDirStat
4. In WinDirStat, delete the file (Recycle Bin or not)   -> APP Crash

Here's a link to procdump Dump  https://1drv.ms/u/s!Al6awteDkZjcm1gp39atg2kQ4JRf?e=S1TFNH

**Comment by NoMoreFood** [comment]
Yes, this was reported and fixed in a subsequent build.  Can you see if it's still a problem for you on the latest?

**Comment by vittoso** [comment]
It works fine on 2024-04-04. I missed the new release, sorry for wasting your time.

**Comment by NoMoreFood** [comment]
No worries.  I appreciate the time you spend reporting issues.
