### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by Six0Ne** [windirstat/windirstat#38]
Does the software support Simplified Chinese? What should I do if it does not?

**Comment by NoMoreFood** [comment]
We do not have a localization file for Chinese.  If your English is strong, we can provide instructions on how to create one and then we could add it to the build.

**Comment by NoMoreFood** [comment]
@Six0Ne I attempted to feed our translation table into ChatGPT.  Can you tell me how this version looks (you may have to select your language from the dropdown under settings):

https://github.com/windirstat/windirstat-next/releases

**Comment by NoMoreFood** [comment]
@Six0Ne Any luck testing?

**Comment by NoMoreFood** [comment]
Marking as closed due to non-responsiveness. I will keep the AI-translated file for simplified Chinese.  Contributors can submit manual tweaks as necessary.
