### ISSUE TITLE
Crash when sort by items

### ISSUE THREAD

**Issue by tron2k** [windirstat/windirstat#39]
Version: 1.3.0-2024-04-04

Steps for reproducing:
- Scan C:
- Sort by Items
- Expand C:\Windows

**Comment by tron2k** [comment]
By the way, is it normal that expanding and closing c:\windows\WinSxS takes some seconds (~4s)?
c:\windows\WinSxS has 164000 items on my disk.

**Comment by NoMoreFood** [comment]
Yes in terms of the time… it’s a lot of stuff to calculate for a list control.  Hopefully we can speed it up a bit when Microsoft fixes their profiler.

**Comment by NoMoreFood** [comment]
Fixed in an internal build (regression from a memory optimization).  Will let you know when there’s a version to test.  Since I am on business travel, that will probably be Saturday.  Thanks!

**Comment by NoMoreFood** [comment]
@tron2k Can you verify the latest build looks good?

https://github.com/windirstat/windirstat-next/releases

**Comment by tron2k** [comment]
There are no crashes in the new version.
