### ISSUE TITLE
Files without extension counted as Local Disk

### ISSUE THREAD

**Issue by tron2k** [windirstat/windirstat#40]
Is it correct that files without extension counted as Local Disk in the Extension list?
![image](https://github.com/windirstat/windirstat/assets/1083527/ab54913c-5006-4629-863a-d29809e955ee)

**Comment by NoMoreFood** [comment]
Yeah I noticed that, too.  I’ll either relabel it or remove it to avoid yet another thing we ought to localize.

**Comment by NoMoreFood** [comment]
@tron2k Can you verify the latest build looks good?

https://github.com/windirstat/windirstat-next/releases

**Comment by tron2k** [comment]
It looks good for me.
