### ISSUE TITLE
Last change date wrong on some Folders

### ISSUE THREAD

**Issue by tron2k** [windirstat/windirstat#41]
![image](https://github.com/windirstat/windirstat/assets/1083527/96c751ec-58eb-47db-acb6-3e0b86d6b534)

![image](https://github.com/windirstat/windirstat/assets/1083527/34e49dcd-4de9-4b76-b33d-0dd29b8a821c)

**Comment by NoMoreFood** [comment]
The date shown *should* be the most recent date anywhere in the child directory structure.  Can you see if it’s coming from an unreadable or corrupt file possibly?

**Comment by tron2k** [comment]
You are right, I found 2 files where the modification date was 2099.
