### ISSUE TITLE
SharePoint and OneDrive sync'd folders linked files show up as taking up space

### ISSUE THREAD

**Issue by JonBeeTheThird** [windirstat/windirstat#42]
We have SharePoint and OneDrive at work, and the files that are linked but not downloaded show up as taking up space in WinDirStat.  Would it be possible to exclude them from the listing or show them as existing but not taking up space.

This would likely apply to other internet-based storage systems like Autodesk Docs, DropBox, etc. that allow you to sync folders/shares down to a local drive.

**Comment by NoMoreFood** [comment]
@JonBeeTheThird 

Please try this release and see if it detects it better.

https://github.com/windirstat/windirstat-next/releases

**Comment by NoMoreFood** [comment]
@JonBeeTheThird  Any luck?

**Comment by JonBeeTheThird** [comment]
@NoMoreFood sorry for the delay.  I have tested with WinDirStat Alpha Build - 2024-04-24 and the sync'd folders no longer show up as taking up space, thank you!  Very impressive speed with the new release as well!

I realize this is scope-creep and may require a new ticket, but would it be possible to show only the the files that have been downloaded from the sync'd location, such as the ones shown with the green check in circle icon below?

![image](https://github.com/windirstat/windirstat/assets/166862669/24326142-08ac-4ed0-801b-305dd71b5edb)

**Comment by NoMoreFood** [comment]
I'll see what it would take.  We have to be careful about those sorts of checks because it can slow down scanning.

**Comment by atsju** [comment]
Just so you know, I encountered same issue on version 1.1.2.80
Beta build: WinDirStat-2.0.0-2024-05-07 fixed the issue but now I miss files compared to windows disk size.

**Comment by Antonimo-Dev** [comment]
Hi, 

Am I missing something in the build 2.1.0 (2024-11-01)?

I do have some SharePoint libraries with only links to the files (symlinks/ Files On-Demand) and I would like to see them in the treemap and folder/file view, but they are not showing up. A folder with Logical Size of 90.6 GB is showing as 72.5 MB Physical Size. Is there a switch or toggle to show the 90.6 GB of files?

**Comment by NoMoreFood** [comment]
No option currently without caching the files.  Most folks are interesting in physical size when it comes to WinDirStat.  What you're asking is basically that we have an option to toggle the try map use logical size.  I'll consider it.

**Comment by Antonimo-Dev** [comment]
@NoMoreFood Thanks for your reply.

I love that you have brought this app back to life and the improvements are great. You also point to other software on the resources page including SpaceSniffer which I took a look at. It has a customisable export script and I managed to download a file list from OneDrive using that.

**Comment by NoMoreFood** [comment]
@JonBeeTheThird  Can you open a separate issue for the feature to have the cloud icon?  Thanks!
