### ISSUE TITLE
"Use this language for date/time and number formatting" meaning reversed

### ISSUE THREAD

**Issue by PEERSOFTdev** [windirstat/windirstat#44]
When checking the "Use this language for date/time and number formatting" checkbox I assume, as the option says, that it will format dates/numbers according to the selected/used UI language, meaning that it would not be the default setting when installed (I had had it off all the time until I tried to play with it).

My observation: Dates/times/numbers have been always formatted the correct way according to my selected language / system locale although this option had been always off. When turning it on, WinDirStat will format according to English rules. I could reproduce the same behaviour with Czech as well as German, for example.

WinDirStat version: 2024-04-16

Windows version/build: Windows 11 build 24100.1

**Comment by NoMoreFood** [comment]
@PEERSOFTdev 

I think I agree. I adjusted the wording a bit in this latest release.  There's been a bunch of new strings added to the application in the last two weeks so if you're fluent in other languages, please feel free to correct anything that ChatGPT couldn't translate for me.

https://github.com/windirstat/windirstat-next/releases

**Comment by PEERSOFTdev** [comment]
I will probably do just the Czech localization as I am not fluent in other languages. Should I create a PR for this localization when complete?

**Comment by NoMoreFood** [comment]
Yeah, same as last time.

**Comment by PEERSOFTdev** [comment]
Well, I don't know who had translated WinDirStat into Czech in the past, but I will do🙆‍♂️.
