### ISSUE TITLE
Wrong Folder Icons

### ISSUE THREAD

**Issue by tron2k** [windirstat/windirstat#45]
Since the last version, there is a bug that displays incorrect folder icons.
![image](https://github.com/windirstat/windirstat/assets/1083527/46c7bea4-a59b-48b0-85eb-c7d2d0c6fa5f)

**Comment by NoMoreFood** [comment]
Ok, I did make a tweak in that area to try to make it multi-threading capable; I will look into it.  Thanks!

**Comment by NoMoreFood** [comment]
Should be addressed in the latest:

https://github.com/windirstat/windirstat-next/releases

**Comment by tron2k** [comment]
It looks good to me.
