### ISSUE TITLE
WinDirStat, mass deployment 

### ISSUE THREAD

**Issue by SimonLarsenCFM** [windirstat/windirstat#46]
Hey 

will like to hear if that are possible to get windirstat into regedit under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall or HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall

i use it normaly to detect metode in sccm and use it for uninstall.

**Comment by NoMoreFood** [comment]
Yes, the next version will have this.  It looks like the Wix install file we already have automatically puts in there.

**Comment by SimonLarsenCFM** [comment]
as i can see the current version put it in "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\WinDirStat"
and will it also be possible to use a MSI and an MSI uninstall instead "C:\Program Files (x86)\WinDirStat\Uninstall.exe"
thats will be alot more easier for me to make the deployment.

**Comment by NoMoreFood** [comment]
@SimonLarsenCFM  Can you test out this version (MSI):

https://github.com/windirstat/windirstat-next/releases/

**Comment by NoMoreFood** [comment]
Uninstalling would be: `msiexec /x "{EB9B4D4D-D88C-424A-87AA-B7EF40BCB072}" /qb`
