### ISSUE TITLE
First-time Portable Mode annoyance

### ISSUE THREAD

**Issue by PEERSOFTdev** [windirstat/windirstat#47]
When I start WinDirStat for the first time (after unzipping), press Escape to dismiss drive selections, go to Settings > General, check the Run in portable mode option and hit OK, then whenever I try to close the application it displays the following error message and does not close:

Encountered an improper argument.

OK

The portable mode file is being created though.

Occurs since the first alpha version I could test.

Encountered in Windows 11 build 26100.1 Czech.

**Comment by NoMoreFood** [comment]
Can you see if operates as desired in the latest build?

https://github.com/windirstat/windirstat-next/releases
