### ISSUE TITLE
Language change does not result in restart warning

### ISSUE THREAD

**Issue by PEERSOFTdev** [windirstat/windirstat#49]
When having Czech set as my language and I switch to English, on pressing OK a warning about the change taking effect upon restart does not appear and the interface language is still Czech. Various other language switching combinations, such as from Czech to German, German to English etc. do produce the correct warning.

The reason behind this difference in behaviour could be that Czech is my primary Windows language and English is my fallback language, so that this bug could then apply to other primary/fallback language pairs.

**Comment by NoMoreFood** [comment]
When this occurs, are you choosing to restart immediately or are you waiting?  Does it seem to make a difference either way?

**Comment by PEERSOFTdev** [comment]
When I switched from Czech to English and the warning did not appear, I tried to restart, saw the interface in English so switched back to Czech, when the warning was displayed. I tried this back-and-forth switch without restart and it worked the same way except that the language did not change to English. I take the warning as a legitimate request (some applications do require it) so it is not normal for me when the warning does not appear, this is why I created the issue.

**Comment by NoMoreFood** [comment]
Could you possible do a screen recording of this so I replicate it precisely?  I can install the Czech binaries for Windows in a VM to reproduce it.

**Comment by PEERSOFTdev** [comment]
Well, I have not much experience with recording the screen or video as I am blind, but I've made at least a recording of the steps to reproduce by using the legacy Windows Problems Step Recorder that I still have on my system and that is most accessible for me. Hope you'll figure out how to get desired information from that.

[WinDirStat_LanguageChangeRecording.zip](https://github.com/windirstat/windirstat/files/15141752/WinDirStat_LanguageChangeRecording.zip)

**Comment by NoMoreFood** [comment]
Thanks, I'm having issues viewing the images but I think I'll be able after some googling.  I'm very much a visual person so this helps.

**Comment by NoMoreFood** [comment]
I've located the issue.  Will have new binaries in a day or two.  Thanks!

**Comment by NoMoreFood** [comment]
@PEERSOFTdev 

Can you try the latest please: https://github.com/windirstat/windirstat-next/releases  ?

**Comment by PEERSOFTdev** [comment]
Yes, now it works as expected :-).
