### ISSUE TITLE
Crash when switching to Administrator via File -> Run Elevated inside WinDirStat  [WinDirStat-1.3.0-2024-04-29\x64]

### ISSUE THREAD

**Issue by vittoso** [windirstat/windirstat#51]
Hi,
In my configuration WinDirStat crashes when using the following repro steps:
1. Launch WinDirStat 2024-04-29 double clicking on the EXE
2. Inside WinDirStat launch "Run Elevated"  via the File menu
3. Accept UAC prompt
4. CRASH

Here's a link to the dump (procdump -ma as post mortem debugger): [OneDrive](https://1drv.ms/u/s!Al6awteDkZjcm3Zk5fxp8niP29-T?e=tq9XIc)

Note that there are no problems if I run the exe by right clicking it and "Run as Administrator" at the first step.

**Comment by NoMoreFood** [comment]
Thanks for the report.  Can you try the latest:

https://github.com/windirstat/windirstat-next/releases/
