### ISSUE TITLE
CSV logical/physical sizes swapped

### ISSUE THREAD

**Issue by PEERSOFTdev** [windirstat/windirstat#53]
When opening a disk drive in WinDirStat, it displays logical and physical sizes correctly (they match with that displayed in File Explorer Properties).

When I save the current view to a CSV file and open in (in the same session or later) it merely swaps data of the physical/logical sizes as shown in the folder view.

I am attaching screenshots. I can send CSV data privately if required.

![screenshot_04-05-2024_11-44-00_Live-View](https://github.com/windirstat/windirstat/assets/97554883/8d6b967a-19dd-437c-af68-0b9e6eedce86)
![screenshot_04-05-2024_11-47-09_CSV-View](https://github.com/windirstat/windirstat/assets/97554883/70d5aaf9-05a3-4baf-9567-d9b16834f77c)

**Comment by NoMoreFood** [comment]
Aye, easy fix. I've made the change in development.  I'm waiting my new code signing certificate so I'll publish a testable version after that.  Thank you for another great find!

**Comment by NoMoreFood** [comment]
@PEERSOFTdev Can you see if the issue is addressed in the latest release?

https://github.com/windirstat/windirstat-next/releases

**Comment by PEERSOFTdev** [comment]
Fixed, thanks!
