### ISSUE TITLE
Windows binaries here on release, not only source code

### ISSUE THREAD

**Issue by svenbolte** [windirstat/windirstat#54]
The binary download on source forge is about 100 years old. There are some forks providing binaries downloads, but it would be nice to have the current develop and release status builds placed here.

**Comment by assarbad** [comment]
Uhm @svenbolte there hasn't been any new _release_ yet, just pre-release versions and they can be found [here](https://github.com/windirstat/windirstat-next/releases).

**Comment by NoMoreFood** [comment]
New release has binaries included.
