### ISSUE TITLE
SourceForge WinDirStat Risk Assesment

### ISSUE THREAD

**Issue by greuwer** [windirstat/windirstat#55]
TMF Health Quality Institute is a federal contractor. We are required to perform a risk assessment of any new product/service.  Who do we contact to get our risk assessment questionnaire completed as well as receiving the supporting artifacts. We understand that we may be required to sign a mutual non-disclosure agreement to obtain the risk assessment artifacts.

[WInDirStat - TMF Vendor Supply Chain Risk Assessment Questionnaire.xlsx](https://github.com/windirstat/windirstat/files/15265030/WInDirStat.-.TMF.Vendor.Supply.Chain.Risk.Assessment.Questionnaire.xlsx)

**Comment by assarbad** [comment]
@greuwer perhaps @NoMoreFood is inclined to help out with this. Quite frankly I am not, no offense intended.

Attaching an _Excel_ file -- a file format known for its less than stellar  security track record (thanks in part to Excel's defaults) -- from an account that has _just joined_ (4 hours ago as of this writing), mere weeks after [the xz debacle](https://tukaani.org/xz-backdoor/) and weeks [after it was pointed out how attaching files to comments can make them appear to be officially associated with a project](https://www.bleepingcomputer.com/news/security/github-comments-abused-to-push-malware-via-microsoft-repo-urls/) really is a red flag to me (day job in IT security). So I'd not even download and open it for that reason alone. Besides, the attempt to visit your website from my location yields this:

![2024-05-09_20-48](https://github.com/windirstat/windirstat/assets/3238620/8e3d15a5-f9ee-4422-9d4c-98e0c71980e3)

(same for the other domain that seems to be associated to your organization)

**Comment by greuwer** [comment]
Please direct me to who I can contact in the security department so we can get our Federally required risk assessment started and completed.

Regards,
Glori

Glori Euwer
Chief Information Security Officer (CISO)
TMF Health Quality Institute
3107 Oak Creek Drive | Suite 200 | Austin, TX 78727-3107
Phone: (512) 485-2211
Email: ***@***.******@***.***>
Website: www.tmf.org<http://www.tmf.org/>
Improving Lives by Improving the Quality of Health Care

From: Oliver Schneider ***@***.***>
Sent: Thursday, May 9, 2024 4:32 PM
To: windirstat/windirstat ***@***.***>
Cc: Glori Euwer ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [windirstat/windirstat] SourceForge WinDirStat Risk Assesment (Issue #55)

.

ATTENTION: This message originated from an EXTERNAL source. Please exercise caution when opening attachments, clicking on links, or replying.

.

________________________________

@greuwer<https://urldefense.us/v3/__https:/github.com/greuwer__;!!DpBz2Dz5-X_NdA!CtKCEJpWj_zRm53Xh8iOuJRiNx52x8HZ29yx64e0JGdd7Q2NM0qRpkoqJdBHY-F1ny_C5Q8ZFnun3X0UU2LxG0Hb$> perhaps @NoMoreFood<https://urldefense.us/v3/__https:/github.com/NoMoreFood__;!!DpBz2Dz5-X_NdA!CtKCEJpWj_zRm53Xh8iOuJRiNx52x8HZ29yx64e0JGdd7Q2NM0qRpkoqJdBHY-F1ny_C5Q8ZFnun3X0UUzV9J7FB$> is inclined to help out with this. Quite frankly I am not, no offense intended.

Attaching an Excel file -- a file format known for its less than stellar security track record (thanks in part to Excel's defaults) -- from an account that has just joined (4 hours ago as of this writing), mere weeks after the xz debacle<https://urldefense.us/v3/__https:/tukaani.org/xz-backdoor/__;!!DpBz2Dz5-X_NdA!CtKCEJpWj_zRm53Xh8iOuJRiNx52x8HZ29yx64e0JGdd7Q2NM0qRpkoqJdBHY-F1ny_C5Q8ZFnun3X0UUyX4SxJh$> and weeks after it was pointed out how attaching files to comments can make them appear to be officially associated with a project<https://urldefense.us/v3/__https:/www.bleepingcomputer.com/news/security/github-comments-abused-to-push-malware-via-microsoft-repo-urls/__;!!DpBz2Dz5-X_NdA!CtKCEJpWj_zRm53Xh8iOuJRiNx52x8HZ29yx64e0JGdd7Q2NM0qRpkoqJdBHY-F1ny_C5Q8ZFnun3X0UUwAgALYL$> really is a red flag to me (day job in IT security). So I'd not even download and open it for that reason alone. Besides, the attempt to visit your website from my location yields this:

2024-05-09_20-48.png (view on web)<https://urldefense.us/v3/__https:/github.com/windirstat/windirstat/assets/3238620/8e3d15a5-f9ee-4422-9d4c-98e0c71980e3__;!!DpBz2Dz5-X_NdA!CtKCEJpWj_zRm53Xh8iOuJRiNx52x8HZ29yx64e0JGdd7Q2NM0qRpkoqJdBHY-F1ny_C5Q8ZFnun3X0UU2PYRjyC$>

(same for the other domain that seems to be associated to your organization)

**Comment by NoMoreFood** [comment]
@greuwer, as a CISO, I expect you would know that most open source software does not have a "security department" at the ready to respond to these inquires. This project has been largely maintained by a single individual, part time for more than a decade. I recently started helping with development (also part time) as my day job is a contractor for the US DoE/Navy.  Many of the questions in that document difficult to answer as it appears they are geared towards commercial software vendors (not one or two people developing free software of out of the goodness of our hearts).

_Usually_ "federally required risk assessment" are only necessary for federal organizations.  What federal department do you fall under?  I am willing to help with this to some degree, but I mainly I think we need you to recalibrate your form for small scale open source software efforts.

**Comment by NoMoreFood** [comment]
Closing; non-responsive.
