### ISSUE TITLE
WinDirStat Next: Treemap does not load after disabling it and a new search

### ISSUE THREAD

**Issue by Medowar** [windirstat/windirstat#57]
Description: Treemap does not display again, after beeing disabled for a search and then getting reenabled.

Steps to reproduce: Open WindirStat with default config, start a search, disable treemap, start another search, enable treemap.

Result: Treemap displays a blank window, even after starting a new search. On the new search, treemap does not display, even though the mark is set in the menu.

Update: Moving the entire window apparently redraws the treemap, when the treemap window-part is visible.

**Comment by NoMoreFood** [comment]
@Medowar Thanks for the feedback. I will look into this.

**Comment by NoMoreFood** [comment]
Can you see if this version behaves better for you?

https://github.com/windirstat/windirstat-next/releases
