### ISSUE TITLE
Individual Folder radio button not focusable

### ISSUE THREAD

**Issue by PEERSOFTdev** [windirstat/windirstat#59]
Common practice in user interfaces is that related radio buttons are being grouped and thus can be navigated via keyboard. In WinDirStat, the NVDA Screen Reader does not indicate a radio group for the "All local disks" and "Individual disks" although they can be selected by Up/Down cursor keys when one of them is focused by a Tab key. The third radio button, "Individual folder", can't be focused in any way via the keyboard. I see that the Individual Disks listview is placed between the radio buttons in windirstat.rc. Could possibly placing the radio buttons adjacent to each other help, like so:

```
    CONTROL         "IDS_DISKS_ALL_LOCAL",IDC_ALLDRIVES,"Button",BS_AUTORADIOBUTTON | WS_GROUP,7,7,99,10
    CONTROL         "IDS_DISKS_LOCAL",IDC_SOMEDRIVES,"Button",BS_AUTORADIOBUTTON,7,31,91,10
    CONTROL         "IDS_DISKS_FOLDER",IDC_AFOLDER,"Button",BS_AUTORADIOBUTTON,7,150,100,10
    CONTROL         "IDS_DISKS_LOCAL",IDC_DRIVES,"SysListView32",LVS_REPORT | LVS_OWNERDRAWFIXED | LVS_ALIGNLEFT | WS_BORDER | WS_TABSTOP,7,43,262,100
```

**Comment by NoMoreFood** [comment]
I think you're right that's how the control lines should be setup so I'll definitely switch that but I think there's also something else going on with the UI logic here that needs to be investigated.

**Comment by NoMoreFood** [comment]
@PEERSOFTdev Can you see if the behavior in the latest release is more in line with your expectations?

https://github.com/windirstat/windirstat-next/releases

**Comment by PEERSOFTdev** [comment]
Yes, when taking into account strictly the issue subject, this behaviour has been fixed. However, the "Individual folder" functionality got broken from the accessibility point of view as I can't select the button that would allow me to browse for the folder. If you want, I will open another bug regarding this behaviour.

**Comment by NoMoreFood** [comment]
That browse capability probably hasn't worked since I switched to CMFCEditBrowseCtrl.  I checked the source code for MFC and the way to get the browse dialog is moving to the control and do Alt+Down or Alt+Right.
