### ISSUE TITLE
Run Elevated does not work

### ISSUE THREAD

**Issue by PEERSOFTdev** [windirstat/windirstat#60]
WinDirStat shuts down while this menu command is being executed.

Steps to reproduce:
1. Start WinDirStat and press Escape when told to select target.
2. From the File menu, click "Run Elevated".
3. When the UAC prompt appears, click Yes.
4. The WinDirStat window now closes.

Launching WinDirStat as administrator via the File Explorer Context Menu works OK.

Unfortunately I found no crash report (tried AppCrashView).

Tried with WinDirStat 2.0 build 2024-05-07 in Windows 11 build 26120.

**Comment by NoMoreFood** [comment]
Can you see if this version addresses your issue?

https://github.com/windirstat/windirstat-next/releases

**Comment by PEERSOFTdev** [comment]
Works as expected, thanks a lot!
