### ISSUE TITLE
Inconsistent file names shown in status line

### ISSUE THREAD

**Issue by RobertK66** [windirstat/windirstat#61]
I am not sure if this was introduced by my quirky code fixes for #22 or if this is another side effect of https://github.com/windirstat/windirstat/commit/2c58b5dec1b2c83936594cc00e0776f1c5b36014 but with your Beta build https://github.com/windirstat/windirstat-next/releases/tag/Release_2_0_0_2024_05_07 i found following inconsistencies:

1.  when moving the mouse over the final chart, the status line shows the single file under the mouse cursor.
2.  when selecting a single block (with the mouse) and slowly moving from this block away -> still 1. applies
3.  when **leaving the chart** with the mouse, the single selected file (!) is shown in the status line
4.  when i do some multiselect with the mouse and leave the chart in this state, the status line switches to 'Bereit' ('ready') 

So far this seems to be consistent but when I start to select nodes in the tree view (no matter if with mouse or with cursor keys) then the status line **is not changed at all**! But the chart clearly selects the tree selection with its white box. If you ever have entered the chart with the mouse before using the tree selection then the content of the status line sticks to an old value (determined by 1-4) and is clearly inconsistent with the white box!

I think there is code - somewhere - fixing this (when leaving the chart with the mouse!) which should also be triggered when the selection gets changed by the tree view.
So when selection goes to 'single file/dir' -> then show this one node name in the status line.
If multiselect -> do not show content (or maybe show something like "[multiple...]" or so...

**Comment by NoMoreFood** [comment]
Yeah, the multi-selection did complicate how that status bar was used (and it was already complicated since it was dependent on both the treemap and the filetree).  I'll take a look soon --- I have some big events with my day job and home so it's slowed me down a bit.  Thanks for testing!

**Comment by NoMoreFood** [comment]
@RobertK66 It's not perfect, but this release should be more consistent:

https://github.com/windirstat/windirstat-next/releases

From my commit: "Make status text update more consistently. It should display the hovered item path when the map has focus, the selected extension when the extension list has focus, the selected item if the file tree or dupe list has focus (and only a single item is selected), or 'Ready' otherwise."

**Comment by RobertK66** [comment]
Looks good. Also the cursor keys seem to work as expected now.
(have not much time to play around now but will give it a try on the weekend...)
