### ISSUE TITLE
Encountered an improper

### ISSUE THREAD

**Issue by HenryGessau** [windirstat/windirstat#62]
![image](https://github.com/windirstat/windirstat/assets/1934506/43d11556-79b6-4c0f-9da7-1fb504c56f7e)

First I scanned all drives on my PC. Then I selected only C: as the target (File -> Select Target), and got this error.

Using the `2024-05-07` release.

**Comment by NoMoreFood** [comment]
Can you see if this version addresses your issue?

https://github.com/windirstat/windirstat-next/releases

**Comment by HenryGessau** [comment]
Fixed in `2024-07-05 beta`
