### ISSUE TITLE
beta "about" window version consistency

### ISSUE THREAD

**Issue by atsju** [windirstat/windirstat#63]
I just downloaded latest beta version and the release naming is not consistent. 
I recommend you take care so that you can more easily track bugs.

- Tag is named **Release_2_0_0_2024_05_07**
- Release title is **WinDirStat Beta Build - 2024-05-07**
- And about windows shows :![image](https://github.com/windirstat/windirstat/assets/4628382/a10ac028-fd95-41c0-bf0e-eb3570dd1de5)
- And zip name is **WinDirStat-2.0.0-2024-05-07**

You probably know https://semver.org/
Maybe automate tag/release/about/zip to use same naming like `2.0.0-Beta20240507`

**Comment by NoMoreFood** [comment]
I added the git commit hash and date to the about box starting in the 2024-07-05 release:

https://github.com/windirstat/windirstat-next/releases

**Comment by atsju** [comment]
Much better. thanks.

Consider adding the information in a zone where the text can be selected. In version 2.0.0.0 9a53, the user must manually copy the version which is error prone
