### ISSUE TITLE
Enhancement Request: Scan multiple drives at the same time

### ISSUE THREAD

**Issue by driscoll42** [windirstat/windirstat#65]
On my machine, I have seven hard drives and connected to four network drives. When I run windirstat, it scans them one at a time. Looking at my network usage and hard drive usage, it's only ~10 MB/s, well below saturating my network or hard drive bandwidth caps. I think when scanning multiple drives, it would be helpful to scan them in parallel. I tried upping the number of threads Windirstat is allowed to use to the max, and that didn't seem to do anything. I wouldn't be shocked if there's some technical limitation here, but wanted to make the ask. Otherwise this works great!

**Comment by NoMoreFood** [comment]
Technically speaking, it's possible it _could_ scan multiple drives depending on how the multithreaded queue is processed.   I think the proper think to do here would for me to spawn the specified number of threads for each drive to distribute the load. I will investigate this.

**Comment by driscoll42** [comment]
@NoMoreFood Aw yeah, this is great! Thanks for your work. Especially for my network drives this scans them all much faster. Appreciate the implementation of it so quickly!
