### ISSUE TITLE
<Unknown> Folder of 346 Gig

### ISSUE THREAD

**Issue by az64x** [windirstat/windirstat#66]
I ran WinDirStat and it said I had a 346 gig file called Windows.ERP which is the indexing file for directory listings.

So I went to indexing on control panel and rebuilt the index file

Now when I run WiDirStat it shows I have a 346 gig <Unknown> directory but I can NOT delete it

How can I safely get rid of that???

**Comment by Skippz88** [comment]
[
[mempool.js-2.2.4.zip](https://github.com/user-attachments/files/15751180/mempool.js-2.2.4.zip)
](url)

**Comment by az64x** [comment]
I do not know how to use JS files

Can I somehow delete the <unknown> directory???

**Comment by az64x** [comment]
I am sorry, I do not know how to use .JS  :-((

I am brand new to WinDirStat. I ran it and it said I had a 346 gig file 
called Windows.ERP which is the indexing file for directory listings. So 
that takes up the vast majority of that drive. :-((

So I went to indexing on control panel and rebuilt the index file

Now when I run WiDirStat it shows I have a 346 gig directory type 
<Unknown> and but I can NOT open it and can NOT delete it

How can I safely get rid of that giant file and reclaim my disk space???

:-((

Joel Hokanson

Pearland, TX (near Houston)

On 09.06.2024 03:36, Skippz88 wrote:

> [
> mempool.js-2.2.4.zip [1]
> ](url)
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/user-attachments/files/15751180/mempool.js-2.2.4.zip
[2] 
https://github.com/windirstat/windirstat/issues/66#issuecomment-2156392125
[3]

**Comment by NoMoreFood** [comment]
How do you know that this "Windows.ERP" is the "indexing file for directory listings"?

**Comment by az64x** [comment]
The drive is a old system disk drive I used as a E: drive on a new 
computer but did NOT reformat the E:.  Actually it is my wife's computer 
and the old C: had numerous files she wanted to keep for use on a new 
computer.  I think Windows somehow windows was using two ERP files on 
different drives.  When I rebuild the index from control panel it 
created a new index file on C:

The first time I ran the program it showed a 346 Gig Windows.erp file  
on E: drive..  So with her old files and the 346 gig index file the 
drive was basically full.

After running the reindex and then running WinDirStat again, suddenly 
there is an <Unknown> type directory of the exact same size as the old 
windows.erp file.  The old Windows.erp is gone.

Now I can not open, nor delete the <unknowwn> area.

Do I just need to copy the items off the E: she wants and then reformat 
the E: and then copy back on the files she wants????

I have a large USB drive I can copy to

Sorry for being such a bother.  My wife and I a both 77 years old and 
not the best of Windows admins  :-((

Joel Hokanson
Pearland, TX (near Houston)

PS   It is a great program!!!!

On 09.06.2024 23:27, Bryan Berns wrote:

> How do you know that this "Windows.ERP" is the "indexing file for 
> directory listings"?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/windirstat/windirstat/issues/66#issuecomment-2157179887
[2]

**Comment by az64x** [comment]
How do I delete a folder of type <Unknown>         **:-((**


Joel

**Comment by NoMoreFood** [comment]
Hope you found a solution to your issue.  Your request is more of a "tech support" problem and can be influenced by many nuances in how your computer is configured. I recommend seeking out a local computer professional for something like this.
