### ISSUE TITLE
Add option for LZX/EXPRESS folder compression using compact.exe

### ISSUE THREAD

**Issue by ThoughtPhotography** [windirstat/windirstat#67]
In my opinion the biggest improvement for WinDirStat would be the ability to compress a folders contents with compact.exe

Everyone knows folders have an advanced attribute to compress contexts to save space but Windows 10 also supports compression using LZX or EXPRESS which can save significantly more space than the default LZNT1 algorithm while still being accessible like normal.
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/compact

Unfortunately, the default algorithm can't be changed and the other options are only available from the command line, but adding the ability to compress a folder in WinDirStat should be pretty easy and would be an ideal place to do it since it already provides a comprehensive overview of the file system

This open-source utility that adds a GUI for compact.exe could be a useful reference for implementing this functionality.
https://github.com/Freaky/Compactor

**Comment by NoMoreFood** [comment]
I've got the menu items added for this. I hope to have a usable demo by Friday once I fully work out how to do it natively (using C API).

**Comment by NoMoreFood** [comment]
Please checkout this release?  At some point I should probably add some intelligence to gray out which options are supported depending on the file systems, but this seems to get the job done in my basic testing.

https://github.com/windirstat/windirstat-next/releases
