### ISSUE TITLE
I think the issue is specifically about a hardware key being used because if you just take a regular password protected key, you could say the solution is to use credentials manager/caching. Because each key access requires physical interaction with the hardware key, credential manager does not work as a cache in this case, at least with my testing.

### ISSUE THREAD

**Issue by Skippz88** [windirstat/windirstat#69]
I think the issue is specifically about a hardware key being used because if you just take a regular password protected key, you could say the solution is to use credentials manager/caching. Because each key access requires physical interaction with the hardware key, credential manager does not work as a cache in this case, at least with my testing.
Without Yubikey, the issue could probably be translated to reducing password prompts for password protected ssh keys without a credentials helper.

_Originally posted by @cen1 in https://github.com/git-lfs/git-lfs/issues/5784#issuecomment-2144458450_

**Comment by NoMoreFood** [comment]
Garbage report.  User reported.
