### ISSUE TITLE
Build instructions missing on github page

### ISSUE THREAD

**Issue by irzyxel** [windirstat/windirstat#7]
Project description / README.md says:

Please refer to the project Wiki page [Building](https://bitbucket.org/windirstat/windirstat/wiki/Building).

Which leads to

This repository has been deleted. Our apologies, but the repository "windirstat/windirstat" has been deleted.

It now lives at https://osdn.net/projects/windirstat/.

which is, umm, weird.

**Comment by assarbad** [comment]
Should be solved. And OSDN has been retired, but it's impossible to control anything over there under the new owner after it got sold (I'll keep trying to remove it, though).
