### ISSUE TITLE
(Unknown)  346 Gig on 500 gig drive

### ISSUE THREAD

**Issue by az64x** [windirstat/windirstat#71]
When I run WinDirStat the top file listed is (Unknown) and is 346 Gig

How do I delete it???

:-((
Joel
JOELH@Pearland.com

**Comment by NoMoreFood** [comment]
"Unknown" is not a file.  It's simply telling you that there is space that WinDirStat cannot identify (usually due to permissions).  You can try running WinDirStat as an administrator to try to scan that area.
