### ISSUE TITLE
Reconsider default setting of 'Skip protected items'

### ISSUE THREAD

**Issue by achtchaern** [windirstat/windirstat#74]
Hi! Please excuse my picky attitude..

I'd strongly vote against skipping protected items per default. Some reasoning:

- It would be more in line with the classic WinDirStat 
- IMO, the target audience for this app are system admins and power users, who probably don't benefit from this setting being opt-out
- Obviously, WinDirStat is a tool which is ultimately being used to free up storage space. As an admin who has cleaned hundreds of systems (with the help of classic WDS), some of the most typical storage hogs are the Installer folder under C:\Windows as well as pagefile.sys and hiberfil.sys, which are all hidden with the default configuration.

If you don't agree with me, please consider the following compromise: You could check for the following registry key values:

- HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\ShowSuperHidden
- HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\Hidden

and set the default setting regarding skipping protected items in WDS on the basis of how the user has set up Explorer. For users who opted out of hiding hidden files (and / or system protected files) in Explorer, the WDS setting should be disabled.

Some context for my nitpicking: I'm a sysadmin who's using the classic WDS on an almost daily basis for cleaning up full(ish) disks, mostly servers. Most of my colleagues also use the old WDS. We simply take the exe, copy it to the target system and start the scan.. I'd like to motivate them to use the new WDS, but this last drawback is keeping me from telling everyone :)

Additionally, please consider re-doing the tab indexes of the Settings -> Advanced menu (repro: repeatedly press the Tab key under Settings -> Advanced and you'll see that the keyboard focus isn't moving downwards in the correct sequence).

Best regards,
achtchaern

**Comment by NoMoreFood** [comment]
Yeah, I think I'm onboard with this... will probably make the change in the next build.

**Comment by NoMoreFood** [comment]
@achtchaern Default changed in this build (you'll need to clear your settings to see it):

https://github.com/windirstat/windirstat-next/releases

**Comment by achtchaern** [comment]
Thank you!!
