### ISSUE TITLE
Version 1.1.2 installer does not properly set version number in the registry - not showing version in Control Panel -> Programs and Features

### ISSUE THREAD

**Issue by ntman1** [windirstat/windirstat#75]
Version 1.1.2 installer does not properly set version number in the registry - not showing version information in Control Panel -> Programs and Features (see attached screenshot). This causes issues with WinGet and other associated tools not properly being able to detect installed versions versus upgrade available version.
<img width="718" alt="WinDirStat Installation issues" src="https://github.com/windirstat/windirstat/assets/33769104/3596defa-8e32-4f3a-a3c5-7c0c870d6ff8">

**Comment by NoMoreFood** [comment]
This will be addressed in the new version that uses an MSI based installer.

**Comment by NoMoreFood** [comment]
Please try the latest version.  You may need to uninstall the prior one manually:

https://github.com/windirstat/windirstat-next/releases/

**Comment by Julio860JVL** [comment]
Hello @NoMoreFood
I came to report this exact same situation and I can confirm the version does show now.

**Comment by seangibbz** [comment]
This has been partially-fixed in subsequent *WinDirStat Beta* releases (formerly WinDirStat-Next), which now register as v2.0.0.

It'd still be recommended for the beta releases to use the version number format `2.0.0.YYYY.MM.DD` (e.g. `2.0.0.2024.10.04`), so that they can be more easily differentiated and externally managed/upgraded (e.g. using winget).

**Comment by NoMoreFood** [comment]
Just for awareness, I am hoping for an official release within the next week or so.  We're just trying to get the website ready for the update and have a few other loose ends to tie up.

**Comment by assarbad** [comment]
Related to #88.
