### ISSUE TITLE
I am not seeing my c drive directory so I can delete dropbox fils 

### ISSUE THREAD

**Issue by Melvalg** [windirstat/windirstat#76]
I am not seeing my c drive directory so I can delete dropbox fils 

I get the following and don't know which menu to select to get my C drive and eventually my dropbox.

WinDirStat is a disk usage statistics viewer and cleanup tool for various versions of Microsoft Windows.
Note: if you are looking for an alternative for Linux, you are looking for [KDirStat](http://kdirstat.sourceforge.net/) (apt-get install kdirstat or apt-get install k4dirstat on Debian-derivatives) or [QDirStat](https://github.com/shundhammer/qdirstat) and for MacOS X it would be [Disk Inventory X](http://www.derlien.com/) or [GrandPerspective](http://grandperspectiv.sourceforge.net/).

Please visit the [WinDirStat blog](https://blog.windirstat.net/) for more up-to-date information about the program.

On start up, it reads the whole directory tree once and then presents it in three useful views:

The directory list, which resembles the tree view of the Windows Explorer but is sorted by file/subtree size,
The treemap, which shows the whole contents of the directory tree straight away,
The extension list, which serves as a legend and shows statistics about the file types.
Screenshot
The treemap represents each file as a colored rectangle, the area of which is proportional to the file's size. The rectangles are arranged in such a way, that directories again make up rectangles, which contain all their files and subdirectories. So their area is proportional to the size of the subtrees. The color of a rectangle indicates the type of the file, as shown in the extension list. The cushion shading additionally brings out the directory structure.

**Comment by NoMoreFood** [comment]
Which version are you using?  Can you post a screenshot of what you see for selecting files?

**Comment by Melvalg** [comment]
How can I find out? I got to the windows box and tried to
find properties but it's not coming up.
 Thank you for your prompt response.
Melva

I asked a friend how I could find it. I have Windows 11 Enterprise.

**Comment by NoMoreFood** [comment]
If you want to delete your DropBox files and you don't know where they are located, I suggest you just delete them in DropBox.  Your deletions should sync locally.  I don't know enough about DropBox to provide more detailed information.

**Comment by Melvalg** [comment]
ok. yah. drop box does not give instructions.
thanks anyway.
MElva
