### ISSUE TITLE
Request to contribute with Norwegian translation

### ISSUE THREAD

**Issue by nordbymikael** [windirstat/windirstat#78]
Hi,

I did not find the contact info on your website, so I decided to write here.
At the moment, I am an IT operations apprentice at a Norwegian IT company called Evelon.
We use WinDirStat primarily in Microsoft Windows Server operating systems, and I must say that it works impressively well.
I would like to help you with translating WinDirStat to other languages, specifically Norwegian.
If you are interested, I can be contacted at nordby.mikael@gmail.com

Kind regards,
Mikael Nordby
IT operations apprentice

**Comment by NoMoreFood** [comment]
@nordbymikael 

I added an AI-generated version of the Norwegian language file in the latest release:

https://github.com/windirstat/windirstat-next/releases

To modify / tune it:

1. Download the ZIP version of WinDirStat and unzip it
2. Download the language file ([here](https://github.com/windirstat/windirstat)), save it as 'lang_no.txt'
3. Move the 'lang_no.txt' into the same directory as WinDirStat.exe
4. Make modifications to 'lang_no.txt'
5. Restart WinDirStat
