### ISSUE TITLE
Request : Exclude File Symbolic Links

### ISSUE THREAD

**Issue by RFBomb** [windirstat/windirstat#79]
I have a script that we use to de-duplicate files on our computers by creating symbolic links. Through this script my computer has saved 13GB of space. But when using WinDirStat, it follows the links to the target file, resulting in an inflated folder size.

There already exists a toggle in the settings for 'Follow Junction Points'. I am requesting a new setting (false by default) for 'Follow Symbolic Links'. 

I took this screenshot using v1.1.2.80

![image](https://github.com/user-attachments/assets/462f0a93-023f-41d2-af86-44a5cb19be8f)

While I am versed in c#, and not c++, I did some cursory look through of the code here and believe I found where to resolve it:

- [IsFollowingAllowed](https://github.com/windirstat/windirstat/blob/47cbd44fdb132f566009378e57114ce5b96a7151/windirstat/WinDirStat.cpp#L115) appears to be specifically designed to evaluate directories. ( use of `IO_REPARSE_TAG_MOUNT_POINT ` )
A new method that is file-specific *may* be required, maybe not though.

Item.cpp
- [CItem* CItem::AddDirectory](https://github.com/windirstat/windirstat/blob/47cbd44fdb132f566009378e57114ce5b96a7151/windirstat/Item.cpp#L1286) specifically uses the `IsFollowingAllowed` call, while the [CItem* CItem::AddFile](https://github.com/windirstat/windirstat/blob/47cbd44fdb132f566009378e57114ce5b96a7151/windirstat/Item.cpp#L1299C1-L1299C22) immediately below it does not. **I believe this is where the check needs to occur.**

[windirstat/DirStatDoc.cpp](https://github.com/windirstat/windirstat/blob/47cbd44fdb132f566009378e57114ce5b96a7151/windirstat/DirStatDoc.cpp#L463)
- [RecursiveUserDefinedCleanup](https://github.com/windirstat/windirstat/blob/47cbd44fdb132f566009378e57114ce5b96a7151/windirstat/DirStatDoc.cpp#L728) also uses this specifically for directories, as a file should reach the `continue` statement below.
```
if (finder.IsDots() || !finder.IsDirectory())
        {
            continue;
        }
```
- [RecurseRefreshReparsePoints](https://github.com/windirstat/windirstat/blob/47cbd44fdb132f566009378e57114ce5b96a7151/windirstat/DirStatDoc.cpp#L463) also uses a similar check.
```
if (!child->IsType(IT_DIRECTORY | IT_DRIVE | ITF_ROOTITEM))
            {
                continue;
            }
```

**Comment by NoMoreFood** [comment]
Impressive digging.  This seems reasonable and I will consider adding it.  File symbolic links on Windows aren't very popular outside of the uber nerd community so I hadn't considered adding it.

**Comment by NoMoreFood** [comment]
So the next 2.0 beta release today will have this option included, but I will tell you that the way the new scanner works that symbolic links already register as 0-bytes so this new option will basically only hide the files.

**Comment by RFBomb** [comment]
Ah, I had downloaded off of sourceforge, which had been reporting the linked file size instead of 0. So I'm assuming the new scanner is still beta ?

**Comment by NoMoreFood** [comment]
@RFBomb Yes, still in beta but getting pretty close to release.  Latest version is here:

https://github.com/windirstat/windirstat-next/releases

**Comment by vittoso** [comment]
If useful, I don't think version WinDirStat-2.0.0-2024-07-22 doing this, but I will check it  when possible.
