### ISSUE TITLE
Datetime format

### ISSUE THREAD

**Issue by reukiodo** [windirstat/windirstat#80]
I do not think this is related to https://github.com/windirstat/windirstat/issues/44 and it is the only issue I could find related to datetime format displayed.

My system is set to English and use ISO-8601 datetime format, however WinDirStat refuses to do so. Any settings in Windows' Region date & time format settings seem to be completely ignored. Does WinDirStat completely disregard Windows date and time format settings?

WinDirStat should just use date & time format settings from Windows.

**Comment by NoMoreFood** [comment]
@reukiodo Can you confirm which version of WinDirStat you are using?

**Comment by NoMoreFood** [comment]
Also, if you could please provide a screenshot of what your date/time settings are in Windows, what your times are showing up in WinDirStat (screenshot), and whether you have the option to use the fallback time in the settings enabled or not?

**Comment by Avaruz** [comment]
It seems that WindirStat uses its own language setting for formatting:
This is in spanish:
![image](https://github.com/user-attachments/assets/2313f853-fe78-4bc7-a90b-5c6b310e5c84)
This is in english:
![image](https://github.com/user-attachments/assets/795719af-15d4-4f23-8041-8f2cbd1881e3)

In both cases my Regional Settings is Spanish(Bolivia):
![image](https://github.com/user-attachments/assets/e9508ecd-24ba-4591-a64b-6abf88b884b8)

This is my version:
![image](https://github.com/user-attachments/assets/0ba75116-fd65-4415-8d9d-2016807909e7)

**Comment by NoMoreFood** [comment]
@Avaruz So, to confirm, do you concur that the first screenshot looks correct?  It seems to match your language settings.

![image](https://github.com/user-attachments/assets/9df531d9-f00c-467e-a7ec-2780f0a028ce)

**Comment by NoMoreFood** [comment]
@reukiodo  I believe the behavior now should be more intuitive. 
 Basically the checkbox (which is now enabled by default) should use the Windows user setting. Otherwise it will use the defaults for the specified language.  Check out the latest build please: https://github.com/windirstat/windirstat/releases

**Comment by reukiodo** [comment]
![image](https://github.com/user-attachments/assets/7abc72cf-c84e-4482-aded-6395c99beac4)
This checkbox which was previously labeled 'Use fallback language for date/time and number formatting' and in the current build is labeled 'Use Windows settings for date, time, and number formatting' ?

**Comment by reukiodo** [comment]
Thank you for making the default respect the Windows settings!
