### ISSUE TITLE
[WinDirStat-Next, Bug] Keyboard Left Arrow Doesn't go up one level.

### ISSUE THREAD

**Issue by BiatuAutMiahn** [windirstat/windirstat#81]
Hello I noticed that on WinDirStat-Next, when pressing the left arrow in the tree the currently selection does not go up to the parent subtree item unless your are on the topmost item.

**Comment by NoMoreFood** [comment]
@BiatuAutMiahn  I think it's working as I'd expect it to.  Can you elaborate?  Also, which version are you using?

**Comment by NoMoreFood** [comment]
Please reopen if you're still seeing this issue, possible with a video.  Thanks!
