### ISSUE TITLE
Feature Request: Last Date Accessed Support

### ISSUE THREAD

**Issue by JustinJayL** [windirstat/windirstat#83]
I was thinking that it would be nice if the diagram had an option to weight the size of the boxes by last access date as well as size. If you have the option enabled, windows does track the last time you opened a file.

For example, a 10 gigabyte file that hasn't been opened in 3 years might be more important to take a look at than a 20 gigabyte file that you opened today.

Note that this is different than the modified date.

**Comment by assarbad** [comment]
I guess we'd first have to figure out if last time accessed gets updated by AV on-demand scans (from experience I know it usually doesn't for on-access). If it does, the whole feature is moot as it would be skewed by the AV used by the respective user.

But I can see how this makes sense if the data can be relied upon.

**Comment by JustinJayL** [comment]
I just tested it, it looks like on default Windows Defender (Windows 11), running a custom scan will update file accessed time. I never use Custom or Full scan, rather relying on auto scan when a new file gets created or a quick scan. I don't know how common this is, however.

**Comment by NoMoreFood** [comment]
Indexing would also likely access these times.  The scanning process already reads this data (FILE_DIRECTORY_INFORMATION::LastAccessTime), but I don't think I'd be interested in incorporating it given the lack of consistency.  It would like just cause more confusion for those not savvy enough to understand all the stuff that could possibly modify the date.

**Comment by NoMoreFood** [comment]
Since this is not really going to be implementable due to Windows being Windows, I'm going to go head and close this issue.
