### ISSUE TITLE
Add support for Windows ARM64

### ISSUE THREAD

**Issue by Max-RM** [windirstat/windirstat#84]
Hi. I'm using Windows 11 ARM64. Can you make native exe for this platform? Because build-in x86-arm translator is bad, native port will work much more better.
![IMG_20240913_125015](https://github.com/user-attachments/assets/76d29dad-26a1-4698-9950-11c78c48b365)

**Comment by NoMoreFood** [comment]
@Max-RM Before I add it to the official beta build, can you try the ARM/ARM64 files here:

[NewArchBuilds.zip](https://github.com/user-attachments/files/17005211/NewArchBuilds.zip)

**Comment by Max-RM** [comment]
> Before I add it to the official beta build, can you try the ARM/ARM64 files here:

Yes I can. Thx

**Comment by Max-RM** [comment]
> @Max-RM Before I add it to the official beta build, can you try the ARM/ARM64 files here:
> 
> [NewArchBuilds.zip](https://github.com/user-attachments/files/17005211/NewArchBuilds.zip)

WTF bro. Those version MUCH MORE FASTER.

In x86 Version it takes 3:
<img width="1200" alt="image_2024-09-13_20-55-01" src="https://github.com/user-attachments/assets/f218a8c7-dd8b-4fb1-af72-c0a317e361aa">
09

In ARM32 Verison it takes 9 seconds:
<img width="1200" alt="image_2024-09-13_20-57-32" src="https://github.com/user-attachments/assets/201e9bf5-5d13-4afa-962c-e2a8f3831593">

In ARM64 Version it takes 8 seconds:
<img width="1200" alt="image_2024-09-13_20-59-12" src="https://github.com/user-attachments/assets/c49f9c90-d96c-4127-80eb-cd2cab774acf">


Thank you.

**Comment by NoMoreFood** [comment]
I don't have a device that size, but it might not hurt to up the DPI scaling if that's an option.

**Comment by NoMoreFood** [comment]
Now in the "official" beta release: https://github.com/windirstat/windirstat-next/releases
