### ISSUE TITLE
windirstat-next treating links as normal directories when running on Linux through Wine

### ISSUE THREAD

**Issue by FeralHedgehog** [windirstat/windirstat#85]
Hello! Thank you for this awesome program!  
I've been successfully running WinDirStat v1.1.2 on Linux through Wine for quite a while and recently discovered the windirstat-next betas.  
Tried it out and it seems that the newer version incorrectly detects symbolic links as normal directories, leading to incorrect sizes and sometimes endless recursive scans (when a symbolic link points at the current directory).  
The same behavior does not occur on v1.1.2, which correctly marks symlinks with a green chain icon and reports their size as 0.  
The behavior is the same for both x86 and x86_64 builds.  
Sorry if this is out of scope for the project - hopefully it's somehow relevant for Windows as well.  

Build: https://github.com/windirstat/windirstat-next/releases/tag/Release_2_0_0_2024_09_19
Wine version: `wine-9.17`
OS: Arch Linux

**Comment by NoMoreFood** [comment]
Which type of filesystem is hosting the symlinks?   Is following symlinks enabled in the options?

**Comment by NoMoreFood** [comment]
I was able to reproduce this.  This is a consequence of the new version providing granularity between different kinds of reparse points.  The old version does not query the link for the kind of link it is (other than not being a mount point). It appears that Wine does not implement the functionality to discern different types of links (e.g., FSCTL_GET_REPARSE_POINT).  I do not see any way to address this without patching Wine.

**Comment by FeralHedgehog** [comment]
I understand. Thank you for the investigation and the detailed explanation!
