### ISSUE TITLE
WinGet automation with komac and/or winget-release to submit PR to winget-pkgs upon release

### ISSUE THREAD

**Issue by assarbad** [windirstat/windirstat#88]
Using this ticket to prepare for the automation of submitting to `winget-pkgs` and document the process for future reference (@NoMoreFood).

Okay, we have two choices for manifest creation:

1. [`komac`](https://github.com/russellbanks/Komac)
2. [`winget-release`](https://github.com/vedantmgoyal9/winget-releaser) (which uses `komac` under the hood)

Current _release_ version lives at: https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/WinDirStat/WinDirStat as `1.1.2`.

## Keep in mind

**ATTENTION:** However, to get `winget-releaser` automation going our first manifest needs to be created "manually" (i.e. directly use `komac`). The existing 1.1.2 is incompatible (different installer technology, not the same architectures). Subsequent releases can likely be automated.

**NB:** When doing that use an environment variable `GITHUB_TOKEN` with a (classic!) personal access token so that `komac` can access everything as needed. Alternatively the subcommands offer a `--token` switch where needed.

## Creating a new manifest with `komac`

Here's what I was test-running (`komac` is cross-platform) from Linux with Bashisms, split on multiple lines for readability and adapted to the `windirstat/windirstat` and the upcoming 2.0.0 case:

```
PRJ="https://github.com/windirstat/windirstat"
VER=2.0.0
komac new WinDirStat.WinDirStat \
  --package-locale en-US \
  --copyright "Copyright © 2004-2024 WinDirStat Team (windirstat.net)" \
  --copyright-url $PRJ/blob/master/LICENSE.md \
  --publisher "The WinDirStat Team" \
  --publisher-url https://windirstat.net/ \
  --publisher-support-url $PRJ/issues/new \
  --package-name WinDirStat \
  --package-url $PRJ/releases/tag/release/v$VER \
  --author "The WinDirStat Team" \
  --moniker windirstat \
  --license GPL-2.0 \
  --license-url $PRJ/blob/HEAD/LICENSE.md \
  --short-description "WinDirStat is a disk usage statistics viewer and cleanup tool for various versions of Microsoft Windows." \
  --description "Description" \
  --release-notes-url $PRJ/releases/tag/release/v$VER \
  -v $VER \
  -u $PRJ/releases/download/release/v$VER/WinDirStat-{arm,arm64,x64,x86}.msi
```

in case you're unfamiliar with Bash, `$PRJ/releases/download/release/v$VER/WinDirStat-{arm,arm64,x64,x86}.msi` expands to:

```
https://github.com/windirstat/windirstat/releases/download/release/v2.0.0/WinDirStat-arm.msi https://github.com/windirstat/windirstat/releases/download/release/v2.0.0/WinDirStat-arm64.msi https://github.com/windirstat/windirstat/releases/download/release/v2.0.0/WinDirStat-x64.msi https://github.com/windirstat/windirstat/releases/download/release/v2.0.0/WinDirStat-x86.msi
```

where `release/v2.0.0` is the hypothetical tag name for the release.

Here is the full command, expanded into one long line:

```
komac new WinDirStat.WinDirStat --package-locale en-US --copyright 'Copyright © 2004-2024 WinDirStat Team (windirstat.net)' --copyright-url https://github.com/windirstat/windirstat/blob/master/LICENSE.md --publisher 'The WinDirStat Team' --publisher-url https://windirstat.net/ --publisher-support-url https://github.com/windirstat/windirstat/issues/new --package-name WinDirStat --package-url https://github.com/windirstat/windirstat/releases/tag/release/v2.0.0 --author 'The WinDirStat Team' --moniker windirstat --license GPL-2.0 --license-url https://github.com/windirstat/windirstat/blob/HEAD/LICENSE.md --short-description 'WinDirStat is a disk usage statistics viewer and cleanup tool for various versions of Microsoft Windows.' --description Description --release-notes-url https://github.com/windirstat/windirstat/releases/tag/release/v2.0.0 -v 2.0.0 -u https://github.com/windirstat/windirstat/releases/download/release/v2.0.0/WinDirStat-arm.msi https://github.com/windirstat/windirstat/releases/download/release/v2.0.0/WinDirStat-arm64.msi https://github.com/windirstat/windirstat/releases/download/release/v2.0.0/WinDirStat-x64.msi https://github.com/windirstat/windirstat/releases/download/release/v2.0.0/WinDirStat-x86.msi
```

PS: let's see whether [this](https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/WinDirStat/WinDirStat/Beta/2.0.0.2024.10.04) will cause interesting problems for us, I hope not (FYI @seangibbz). Theoretically this establishes a new identifier `WinDirStat.WinDirStat.Beta` and should not interfere, but users of one "channel" cannot use the other and upgrade codes in the MSI may cause conflicts but also the choice of package version ... sigh (I've seen this sort of conflict with Python versions for example). Time will tell.

**Comment by assarbad** [comment]
The output of the komac run is as follows:

```
Latest version of WinDirStat.WinDirStat: 1.1.2
> Custom installer switch:
> Custom installer switch:
> Custom installer switch:
> Custom installer switch:
> Install modes: Interactive, Silent, SilentWithProgress
> Installer success codes:
> Upgrade behaviour: UninstallPrevious
> Commands:
> Protocols:
> File extensions:
> Tags: cleanup, disk-usage, kdirstat, organization, sequoiaview, statistics
# Created with komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: WinDirStat.WinDirStat
PackageVersion: 2.0.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2024-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/windirstat/windirstat/releases/download/release/v2.0.0/WinDirStat-x86.msi
  InstallerSha256: 42EEAF7922C179F87045688D25CDDAA039B504A2C6FF62366D020C05A4D583E9
  ProductCode: '{E082118C-72E3-473C-9C20-59247A5FF22E}'
  AppsAndFeaturesEntries:
  - DisplayName: WinDirStat
    Publisher: WinDirStat Team
    DisplayVersion: 2.0.0
    ProductCode: '{E082118C-72E3-473C-9C20-59247A5FF22E}'
    UpgradeCode: '{E211CCFB-D706-4919-B2FF-0F7F426EA27B}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/WinDirStat'
- Architecture: x64
  InstallerUrl: https://github.com/windirstat/windirstat/releases/download/release/v2.0.0/WinDirStat-x64.msi
  InstallerSha256: A7E2ED6EC3B31075F4214E35A42B66364C9284C1842D6821C26CA03CA2D40E89
  ProductCode: '{047AF572-9AE3-49F4-AE96-E3EC82E98BD3}'
  AppsAndFeaturesEntries:
  - DisplayName: WinDirStat
    Publisher: WinDirStat Team
    DisplayVersion: 2.0.0
    ProductCode: '{047AF572-9AE3-49F4-AE96-E3EC82E98BD3}'
    UpgradeCode: '{E211CCFB-D706-4919-B2FF-0F7F426EA27B}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WinDirStat'
- Architecture: arm
  InstallerUrl: https://github.com/windirstat/windirstat/releases/download/release/v2.0.0/WinDirStat-arm.msi
  InstallerSha256: C9C06102C90713B4CBB6B9BB614D8137CDD937E0BBBD015D2206291A2A488AEC
  ProductCode: '{64AB1261-6A61-41A1-8CF7-582D450765F8}'
  AppsAndFeaturesEntries:
  - DisplayName: WinDirStat
    Publisher: WinDirStat Team
    DisplayVersion: 2.0.0
    ProductCode: '{64AB1261-6A61-41A1-8CF7-582D450765F8}'
    UpgradeCode: '{E211CCFB-D706-4919-B2FF-0F7F426EA27B}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/WinDirStat'
- Architecture: arm64
  InstallerUrl: https://github.com/windirstat/windirstat/releases/download/release/v2.0.0/WinDirStat-arm64.msi
  InstallerSha256: 8C4C686D4F641945168480DAB608F0FEB26182A791F0083AC51E8BC8614B5D9F
  ProductCode: '{5E5F58FC-48C8-490B-BF06-E7C52C14B9FB}'
  AppsAndFeaturesEntries:
  - DisplayName: WinDirStat
    Publisher: WinDirStat Team
    DisplayVersion: 2.0.0
    ProductCode: '{5E5F58FC-48C8-490B-BF06-E7C52C14B9FB}'
    UpgradeCode: '{E211CCFB-D706-4919-B2FF-0F7F426EA27B}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WinDirStat'
ManifestType: installer
ManifestVersion: 1.6.0

# Created with komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: WinDirStat.WinDirStat
PackageVersion: 2.0.0
PackageLocale: en-US
Publisher: The WinDirStat Team
PublisherUrl: https://windirstat.net/
PublisherSupportUrl: https://github.com/windirstat/windirstat/issues/new
Author: The WinDirStat Team
PackageName: WinDirStat
PackageUrl: https://github.com/windirstat/windirstat/releases/tag/release/v2.0.0
License: GPL-2.0
LicenseUrl: https://github.com/windirstat/windirstat/blob/HEAD/LICENSE.md
Copyright: Copyright © 2004-2024 WinDirStat Team (windirstat.net)
CopyrightUrl: https://github.com/windirstat/windirstat/blob/master/LICENSE.md
ShortDescription: WinDirStat is a disk usage statistics viewer and cleanup tool for various versions of Microsoft Windows.
Description: Description
Moniker: windirstat
Tags:
- cleanup
- disk-usage
- kdirstat
- organization
- sequoiaview
- statistics
ReleaseNotesUrl: https://github.com/windirstat/windirstat/releases/tag/release/v2.0.0
ManifestType: defaultLocale
ManifestVersion: 1.6.0

# Created with komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: WinDirStat.WinDirStat
PackageVersion: 2.0.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0

> What would you like to do with WinDirStat.WinDirStat 2.0.0? Exit
```
As individual files we get (needed to zip them up because Github rejects .xml): [WinDirStat.WinDirStat.zip](https://github.com/user-attachments/files/17299830/WinDirStat.WinDirStat.zip)

* `WinDirStat.WinDirStat.installer.yaml`
* `WinDirStat.WinDirStat.locale.en-US.yaml`
* `WinDirStat.WinDirStat.yaml`

**PLEASE NOTE:** the `Description` field needs fixing ... still. Wasn't sure how to best get multiple lines in without "cheating".

**Comment by assarbad** [comment]
## winget-release automation

A potential `.github/workflows/publish-to-winget-pkgs.yml` (Github action) could look as follows in subsequent releases (first one must be semi-manual as outlined above):

```yaml
name: Publish release tags to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Get version
        id: get-version
        run: |
          # Finding the version from release name
          $VERSION="${{ github.event.release.name }}" -replace '^.*/ '
          "version=$VERSION" >> $env:GITHUB_OUTPUT
        shell: pwsh
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: WinDirStat.WinDirStat
          version: ${{ steps.get-version.outputs.version }}
          installers-regex: '\.msi$' # Only .msi files
          token: ${{ secrets.WINGET_TOKEN }}
```

We could also get this done with with `ubuntu-latest` and Bash for the runner and script part.

The `WINGET_TOKEN` needs to be created and registered in the repo _which does the release_. For good measure we need to clone `winget-pkgs` on the same user or set via `fork-user` it as per the README for [winget-releaser](https://github.com/vedantmgoyal9/winget-releaser). It's already forked to this org and set up with the Pull app. That `winget-pkgs` fork is going to be the _source_ of the PR filed at `microsoft/winget-pkgs`.

1. Head to https://github.com/settings/tokens and create a new (classic) personal access token with _only_ the `public_repo` scope activated for it
2. In https://github.com/windirstat/windirstat/settings/secrets/actions create a secret named WINGET_TOKEN (as per vedantmgoyal9/winget-releaser)
3. Commit the above action as `.github/workflows/publish-to-winget-pkgs.yml`
4. Create a (subsequent) release — remember that the initial 2.0.0 release will have to be done via `komac` directly.

**Comment by assarbad** [comment]
One thing that isn't entirely clear if the tag name needs to be encoded `release%2Fv2.0.0` in the URLs or whether `release/v2.0.0` is fine. The latter seems to work at least.

**Comment by assarbad** [comment]
@seangibbz: just wondering, since you took the initiative with microsoft/winget-pkgs#178072, we could perhaps create a separate Github action for betas. It requires a few adjustments on my YAML (different pattern for the tags), but other than that we should be able to get it going. What's your opinion on that?

... and yours, @NoMoreFood?

**Comment by NoMoreFood** [comment]
> One thing that isn't entirely clear if the tag name needs to be encoded `release%2Fv2.0.0` in the URLs or whether `release/v2.0.0` is fine. The latter seems to work at least.

If we want to rework the tagging to use a dash instead, I'm fine with that.

**Comment by sitiom** [comment]
Winget and Scoop maintainer here, I can help update both Winget and Scoop manifests once 2.0.0 is released.

> ```yaml
>           $VERSION="${{ github.event.release.name }}" -replace '^.*/ '
> ```

The `version` input should not contain the `v` prefix, so the regex should be `'^.*/v'`

**Comment by seangibbz** [comment]
> @seangibbz: just wondering, since you took the initiative with [microsoft/winget-pkgs#178072](https://github.com/microsoft/winget-pkgs/pull/178072), we could perhaps create a separate Github action for betas. It requires a few adjustments on my YAML (different pattern for the tags), but other than that we should be able to get it going. What's your opinion on that?
> 
> ... and yours, @NoMoreFood?

I've been doing the pull/push requests manually, but would be happy to make any tag adjustments as necessary

**Comment by assarbad** [comment]
> > ```yaml
> >           $VERSION="${{ github.event.release.name }}" -replace '^.*/ '
> > ```
> 
> The `version` input should not contain the `v` prefix, so the regex should be `'^.*/v'`

Well spotted. Actually I [had this already](https://github.com/assarbad/windirstat/blob/master/.github/workflows/publish-to-winget-pkgs.yml), but somehow copied an older version.

> I've been doing the pull/push requests manually, but would be happy to make any tag adjustments as necessary

We can take it from here. Just wanted to ask if it'd be fine with you if we took your `WinDirStat.WinDirStat.Beta` manifest and used it as a basis for (beta) release automation.

So far we haven't done any _releases_ of the beta, although they were _published_. The difference matters in this part of the `winget-release` GitHub action `.yaml`:

```yaml
  release:
    types: [released]
```

... I believe for beta versions we'd use `types: [published]` and would then match for a different tag name.

**Comment by assarbad** [comment]
For reference, #91 and #92 add the actions already. The next beta by @NoMoreFood will prove if it works.

The only uncertainty now is whether the release action is also properly authored. And most likely the first run for the release action is going to fail due to the manual intervention required (outlined above).

**Comment by assarbad** [comment]
microsoft/winget-pkgs#182350 updates the `WinDirStat.WinDirStat.Beta` manifest, but got "manually" submitted with the help of Komac:

```
$ komac update WinDirStat.WinDirStat.Beta --version 2.0.0.2024-10-12 --urls https://github.com/windirstat/windirstat/releases/download/beta%2Fv2.0.0%2F2024-10-12/WinDirStat-{arm,arm64,x64,x86}.msi
```

**Comment by assarbad** [comment]
The following got triggered by our action, but I had to edit it after the fact to rectify some issues with it: microsoft/winget-pkgs#183283

**Comment by sitiom** [comment]
> Winget and Scoop maintainer here, I can help update both Winget and Scoop manifests once 2.0.0 is released.

I have now updated the corresponding Scoop manifest: https://github.com/ScoopInstaller/Extras/commit/86123eb8b9ca33cf5afe6af7a8608efa4c33f162

**Comment by assarbad** [comment]
@sitiom are you aware of a solution similar to Komac for Scoop? I.e. do you think it is feasible to automate Scoop in a similar fashion? I am interested in both Scoop and Chocolatey. But the latter — I think — wraps stuff its own way so may be out of scope for us. Someone could probably use the portable version for that purpose.

**Comment by sitiom** [comment]
The Scoop manifest ([`windirstat`](https://scoop.sh/#/apps?q=windirstat&id=b5aa023e85648a60aeda76eef2aed1e75dc44a76)) is already being auto updated by the bucket itself. The [Excavator](https://github.com/ScoopInstaller/Extras/actions/workflows/excavator.yml) workflow is run every 4 hours and checks for the [`autoupdate`](https://github.com/ScoopInstaller/Extras/blob/adfbea39e5794c13408295d19fb13ae9a834eb6f/bucket/windirstat.json#L29-L34) field to check for updates. You can open a PR to make changes to the manifest if needed (like Winget).

**Comment by assarbad** [comment]
> The Scoop manifest ([`windirstat`](https://scoop.sh/#/apps?q=windirstat&id=b5aa023e85648a60aeda76eef2aed1e75dc44a76)) is already being auto updated by the bucket itself. The [Excavator](https://github.com/ScoopInstaller/Extras/actions/workflows/excavator.yml) workflow is run every 4 hours and uses the [`autoupdate`](https://github.com/ScoopInstaller/Extras/blob/adfbea39e5794c13408295d19fb13ae9a834eb6f/bucket/windirstat.json#L29-L34) field to check for updates. You can open a PR to make changes to the manifest if needed (like Winget).

Thank you, @sitiom. Much obliged!

**Comment by assarbad** [comment]
@sitiom I added a mention of the option to install with Scoop to the profile page. I'll also add it to the README and website, I reckon.
