### ISSUE TITLE
Error 502 when opening the contact page on the site

### ISSUE THREAD

**Issue by blyamur** [windirstat/windirstat#9]
I understand that this is not entirely about the program, but many places in the instructions and description mention a site page for communication, but when I open it, I get a 502 error over and over again.

https://windirstat.net/contact.html - 502 Bad Gateway - 502 Bad Gateway

I also regularly come across site windirstat.org, is this also yours or does someone use the application in demand?

![Снимок экрана 2024-01-26 101727](https://github.com/windirstat/windirstat/assets/409434/21de518e-ba97-4fe2-9d84-bbaa6a4f8de2)

**Comment by assarbad** [comment]
windirstat.org is not our site, no. No idea who is the impostor here, though.

Thanks for reporting the other issue, I'll tend to it.

**Comment by assarbad** [comment]
Should be fixed. The form has been removed for now. Need to figure out a better option. Reverted to a static page.
