### ISSUE TITLE
v2.01 not working on high-resolution displays

### ISSUE THREAD

**Issue by Twincam99** [windirstat/windirstat#98]
I have installed it [to replace v1] on 3x Win11 Pro machines. The new version works fine on one of them [with a 1920x1080 resolution]. It does not work on either the 2560x1440 nor 3840x2400 resolution systems where it hangs ["not responding" in windows title bar].

I should also add that this was using the 64-Bit version, running as a standard  User. 2 of the systems were running win11 24H2 and one 23H2 [all up-to-date].

**Comment by NoMoreFood** [comment]
I'm hoping this is due to an MFC/OLE bug I just found a workaround for. Can you try the attached?  

[Uploading WinDirStat.zip…]()

**Comment by NoMoreFood** [comment]
@Twincam99 Thanks.  Please let me know how the duplicate file feature works.  It tries to be smart about doing partial hashes before reading the entire file, but the algorithm could probably be improved a bit.

**Comment by Twincam99** [comment]
The "Duplicate" feature appears to work fine. It is possible to sort the columns. It runs for a very long time. I'm not certain, however, that it is too much use - other than revealing a huge amount of duplication in "Edge". The question is "what to do" with them and can they be safely eliminated.

![Count](https://github.com/user-attachments/assets/9a58a8e6-a67a-4100-b875-8e60ae414dc1)

**Comment by NoMoreFood** [comment]
Now available in new release.  Should be in WinGet shortly.
