### ISSUE TITLE
feature request: exclude folders/files from scan

### ISSUE THREAD

**Issue by piotr-kubiak** [windirstat/windirstat#99]
Please allow some option to exclude folders and/or files from scan (and from treemap display).
As an example: I want to scan my C: drive, but I don't care about Windows folder. But it is big, and scanning takes a lot of time.

The same goes for example for  hiberfil.sys. This is a big file, and it takes a lot of "visual space" on the chart. I'd love to be able to somehow exclude it and see everything else.

**Comment by NoMoreFood** [comment]
@piotr-kubiak I know it's not quite what you're asking for, but did you try this option below?  Should exclude many of the items many users may not care about:

![image](https://github.com/user-attachments/assets/dc05225d-9a1c-4ac9-8d8b-312a06dbbc15)

**Comment by piotr-kubiak** [comment]
> @piotr-kubiak I know it's not quite what you're asking for, but did you try this option below?

Yes, I know that option. It is useful, but sometimes I can't set files I would like to hide to protected as it affects other programs as well.

**Comment by georgir** [comment]
Yeah, it would be nice to get a "custom exclude" field in the options. Allow at least full-path exact matches, maybe simple glob patterns, or maybe as advanced as .gitignore syntax, allowing even exceptions to the exceptions (with "!" prefix), etc.

@piotr-kubiak As a temporary workaround, you can export the full scan to csv, filter out the things you don't want from it (i.e. with `find`, `findstr` or even `grep` from git-bash or something) and load it back. It's a lot of steps and it doesn't replace this feature being built-in eventually, but it's something.

On that tangent, being able to control windirstat from the command line might be a good feature to automate such things. Things like what to load or scan, if or where to export the result, exit afterwards or stay open, display progress or stay hidden, etc. Perhaps being able to override some of the settings (and specifically the "custom exclude" proposed above). Guess this deserves a separate ticket.

**Comment by NoMoreFood** [comment]
Yeah, for this I would envision another tab under settings that will allow for a custom exclude filters.  I would probably just use the regular expressions STL functionality.

**Comment by georgir** [comment]
I think regular expressions are a poor choice with their special meaning of `.` and `\` which are common in paths. It's up to you of course, programmers/advanced users will still find them useful, but I think most users would expect glob patterns instead.

**Comment by NoMoreFood** [comment]
@piotr-kubiak This is what I've got planned.  It's mostly functional.  I'm still considering adding context menu options. Think it's missing any essential functionality?

![image](https://github.com/user-attachments/assets/7675db10-ef81-45f5-82c7-a953c1875e72)

**Comment by georgir** [comment]
Will the directories option allow exact full path match and not just name, i.e. exclude `c:\windows` but not `c:\backup\windows`?

I'm not sure there's a need for separate fields for files and directories, there rarely are files without extension or directories with extension, so a single field would usually be sufficiently clear IMO. And a single field can allow stuff like `C:\Windows\*.cab` or `C:\Windows\**\*.cab` for directory-specific file patterns.

**Comment by NoMoreFood** [comment]
> Will the directories option allow exact full path match and not just name, i.e. exclude `c:\windows` but not `c:\backup\windows`?

As I have programmed it at this moment in time, it would not allow you to distinguish that. I was using Beyond Compare for inspiration and that only does file names.  I'm not interested in trying to fully emulate the .gitignore behavior as it's not known to most folks using WinDirStat.  That said, I do appreciate the scenario you describe.  I think what I'll do is process it as a full-path match if the pattern contains a backslash.

**Comment by georgir** [comment]
Out of curiosity, what library or windows API are you using for the glob filtering? Cos with a cursory search I only found windows APIs that let you use globs for what to include, not what to exclude, and no good third party libraries...

**Comment by NoMoreFood** [comment]
Yeah, it's rudimentary but it should satisfy the vast majority of usage and we can tune it if we need to.  If I were to use a native API, I'd probably use PathMatchSpec() but felt easier to just convert to regex (less checks / decisions to make during the scanning logic).

**Comment by georgir** [comment]
I have a few comments about that:
At the minimum, you should escape all special regex chars which you will not otherwise repurpose as a first step: `\ [ ] ( ) { } | ^ $ .`.
And this only makes a difference if you apply the regex to a full path and not just a filename, but for `?` and `*` I'd use `[^\\/:]` and `[^\\/:]*` instead of `.` or `.*`. Then you can also replace `**` (now effectively `[^\\/:]*[^\\/:]*` or whatever) with `.*` and have globstar functionality.
If you do decide to apply the match to the whole path you might find the version with a single exclude field I mentioned above simpler to implement.

**Comment by NoMoreFood** [comment]
I will incorporate some of your advice on the next round.  For some here's a compiled version if you want to try it:

[beta/2.1.0](https://github.com/windirstat/windirstat/releases/tag/beta%2Fv2.1.0%2F2024-10-29)

**Comment by piotr-kubiak** [comment]
> @piotr-kubiak This is what I've got planned. It's mostly functional. I'm still considering adding context menu options. Think it's missing any essential functionality?

Looks good to me :)

**Comment by NoMoreFood** [comment]
@georgir Quickly incorporated your suggestions but didn't have time to test much:

https://github.com/windirstat/windirstat/releases/tag/beta/v2.1.0/2024-11-01

**Comment by NoMoreFood** [comment]
@georgir Any additional thoughts?

**Comment by NoMoreFood** [comment]
Released with https://github.com/windirstat/windirstat/releases/tag/release/v2.1.1
